classdef FileContentsChain < pm.sampling.FileContentsSample
    %
    %   This is the base class for generating objects
    %   that contain the contents of a chain file
    %   generated by a ParaMonte sampler.
    %
    %   This class is meant to be primarily internally
    %   used by the ParaMonte MATLAB library samplers.
    %
    %   Parameters
    %   ----------
    %
    %       See the documentation of the class constructor.
    %
    %   Attributes
    %   ----------
    %
    %       See below for information on the attributes (properties).
    %
    %   Methods
    %   -------
    %
    %       See below for information on the methods.
    %
    %   Returns
    %   -------
    %
    %       An object of class ``pm.sampling.FileContentsChain``.
    %
    %   Interface
    %   ---------
    %
    %       contents = pm.sampling.FileContentsChain(file)
    %       contents = pm.sampling.FileContentsChain(file, [])
    %       contents = pm.sampling.FileContentsChain(file, silent)
    %       contents = pm.sampling.FileContentsChain(file, [], sep)
    %       contents = pm.sampling.FileContentsChain(file, silent, sep)
    %
    %   LICENSE
    %   -------
    %
    %       https://github.com/cdslaborg/paramonte/blob/main/LICENSE.md
    %
    properties(Access = public)
    end

    properties(Hidden)
    end

    methods(Access = public)

        function self = FileContentsChain(file, silent, sep)
            %
            %   Return a scalar object of class ``pm.sampling.FileContentsChain``.
            %
            %   This is the constructor of the class ``pm.sampling.FileContentsChain``.
            %
            %   Parameters
            %   ----------
            %
            %       file
            %
            %           The input scalar MATLAB string
            %           containing the path to an external file.
            %
            %       silent
            %
            %           See the corresponding argument of ``pm.sampling.FileContentsSample`` class.
            %           (**optional**. The default is set by ``pm.sampling.FileContentsSample``.)
            %
            %       sep
            %
            %           See the corresponding argument of ``pm.sampling.FileContentsSample`` class.
            %           (**optional**. The default is set by ``pm.sampling.FileContentsSample``.)
            %
            %   Returns
            %   -------
            %
            %       self
            %
            %           The output scalar object of class ``pm.sampling.FileContentsChain``.
            %
            %   Interface
            %   ---------
            %
            %       contents = pm.sampling.FileContentsChain(file)
            %       contents = pm.sampling.FileContentsChain(file, [])
            %       contents = pm.sampling.FileContentsChain(file, silent)
            %       contents = pm.sampling.FileContentsChain(file, [], sep)
            %       contents = pm.sampling.FileContentsChain(file, silent, sep)
            %
            %   LICENSE
            %   -------
            %
            %       https://github.com/cdslaborg/paramonte/blob/main/LICENSE.md
            %
            if nargin < 3
                sep = [];
            end
            if nargin < 2
                silent = [];
            end
            self = self@pm.sampling.FileContentsSample(file, silent, sep);
        end

    end

end