classdef FileContentsProgress < pm.io.FileContentsTabular
    %
    %   This is the base class for generating objects
    %   that contain the contents of a progress file
    %   generated by a ParaMonte sampler.
    %
    %   This class is meant to be primarily internally
    %   used by the ParaMonte MATLAB library samplers.
    %
    %   Parameters
    %   ----------
    %
    %       See the documentation of the class constructor.
    %
    %   Attributes
    %   ----------
    %
    %       See below for information on the attributes (properties).
    %
    %   Methods
    %   -------
    %
    %       See below for information on the methods.
    %
    %   Returns
    %   -------
    %
    %       An object of class ``pm.sampling.FileContentsProgress``.
    %
    %   Interface
    %   ---------
    %
    %       contents = pm.sampling.FileContentsProgress(file)
    %       contents = pm.sampling.FileContentsProgress(file, [])
    %       contents = pm.sampling.FileContentsProgress(file, silent)
    %       contents = pm.sampling.FileContentsProgress(file, [], sep)
    %       contents = pm.sampling.FileContentsProgress(file, silent, sep)
    %
    %   LICENSE
    %   -------
    %
    %       https://github.com/cdslaborg/paramonte/blob/main/LICENSE.md
    %
    properties(Access = public)
    end

    properties(Hidden)
    end

    methods (Access = public)

        function self = FileContentsProgress(file, silent, sep)
            %
            %   Return a scalar object of class ``pm.sampling.FileContentsProgress``.
            %
            %   This is the constructor of the class ``pm.sampling.FileContentsProgress``.
            %
            %   Parameters
            %   ----------
            %
            %       file
            %
            %           The input scalar MATLAB string
            %           containing the path to an external file.
            %
            %       silent
            %
            %           The input scalar MATLAB logical.
            %           if ``true``, all descriptive messages will be suppressed.
            %           Setting this option to ``false`` is particularly useful
            %           in MPI-parallel simulations.
            %           (**optional**, default = ``false``)
            %
            %       sep
            %
            %           The input scalar MATLAB string
            %           containing the field separator used in the file.
            %           (**optional**, default = ``","``)
            %
            %   Returns
            %   -------
            %
            %       self
            %
            %           The output scalar object of class ``pm.sampling.FileContentsProgress``.
            %
            %   Interface
            %   ---------
            %
            %       contents = pm.sampling.FileContentsProgress(file)
            %       contents = pm.sampling.FileContentsProgress(file, [])
            %       contents = pm.sampling.FileContentsProgress(file, silent)
            %       contents = pm.sampling.FileContentsProgress(file, [], sep)
            %       contents = pm.sampling.FileContentsProgress(file, silent, sep)
            %
            %   LICENSE
            %   -------
            %
            %       https://github.com/cdslaborg/paramonte/blob/main/LICENSE.md
            %
            if nargin < 3
                sep = [];
            end
            if nargin < 2
                silent = [];
            end
            self = self@pm.io.FileContentsTabular(file, silent, sep);
        end

    end

end
