function reportProgress(self)

    global  timeElapsedUntilLastReportInSeconds SumAccRateSinceStart sumAccRateLastReport inverseProgressReportPeriod    ...
            numFunCallAcceptedRejectedLastReport numFunCallAccepted_dummy

    if self.isFreshRun
        self.Timer.toc();
        timeElapsedSinceLastReportInSeconds         = self.Timer.total - timeElapsedUntilLastReportInSeconds;
        timeElapsedUntilLastReportInSeconds         = self.Timer.total;
        meanAccRateSinceStart               = SumAccRateSinceStart.acceptedRejected / self.Stats.NumFunCall.acceptedRejected;
        meanAccRateSinceLastReport          = (SumAccRateSinceStart.acceptedRejected - sumAccRateLastReport) * inverseProgressReportPeriod;
        estimatedTimeToFinishInSeconds      = (self.SpecMCMC.chainSize.val - self.Stats.NumFunCall.accepted) * timeElapsedUntilLastReportInSeconds / self.Stats.NumFunCall.accepted;
       
        % self.TimeFile.format
        fprintf ( self.TimeFile.unit    , self.TimeFile.format                      ...
                                        , self.Stats.NumFunCall.acceptedRejected    ...
                                        , self.Stats.NumFunCall.accepted            ...
                                        , meanAccRateSinceStart                     ...
                                        , meanAccRateSinceLastReport                ...
                                        , timeElapsedSinceLastReportInSeconds       ...
                                        , timeElapsedUntilLastReportInSeconds       ...
                                        , estimatedTimeToFinishInSeconds            ...
                                        ) ;
    else
        fprintf ( self.TimeFile.unit    , self.TimeFile.format                      ...
                                        , numFunCallAcceptedRejectedLastReport      ...
                                        , numFunCallAccepted_dummy                  ...
                                        , meanAccRateSinceStart                     ...
                                        , meanAccRateSinceLastReport                ...
                                        , timeElapsedSinceLastReportInSeconds       ...
                                        , timeElapsedUntilLastReportInSeconds       ...
                                        , estimatedTimeToFinishInSeconds            ...
                                        ) ;
    end

    % report progress in the standard output
    
    formatStr   = "            %14d / %8d" + "   " + "%16.4f / %6.4f" + "   " + "%14.4f / %8.4f" ;
    if self.Image.isFirst
        fprintf ( 1, repmat('\b', 1, 93));
        fprintf ( 1, formatStr  , self.Stats.NumFunCall.accepted                                                    ...
                                , self.Stats.NumFunCall.acceptedRejected                                            ...
                                , meanAccRateSinceLastReport                                                        ...
                                , SumAccRateSinceStart.acceptedRejected / self.Stats.NumFunCall.acceptedRejected    ...
                                , timeElapsedUntilLastReportInSeconds                                               ...
                                , estimatedTimeToFinishInSeconds                                                    ...
                                ) ;
    end

    numFunCallAcceptedRejectedLastReport    = self.Stats.NumFunCall.acceptedRejected;
    sumAccRateLastReport                    = SumAccRateSinceStart.acceptedRejected;

end
