program example

    use pm_kind, only: LK
    use pm_kind, only: SK ! All kinds are supported.
    use pm_kind, only: IK ! All kinds are supported.
    use pm_kind, only: CK ! All kinds are supported.
    use pm_kind, only: RK ! All kinds are supported.
    use pm_io, only: display_type
    use pm_option, only: getOption

    implicit none

    character(3, SK), allocatable   :: Optional_SK(:,:), Default_SK(:,:), Output_SK(:,:)    ! Can be any processor-supported kind.
    logical(LK)     , allocatable   :: Optional_LK(:,:), Default_LK(:,:)                    ! Can be any processor-supported kind.
    integer(IK)     , allocatable   :: Optional_IK(:,:), Default_IK(:,:)                    ! Can be any processor-supported kind.
    complex(CK)     , allocatable   :: Optional_CK(:,:), Default_CK(:,:)                    ! Can be any processor-supported kind.
    real(RK)        , allocatable   :: Optional_RK(:,:), Default_RK(:,:)                    ! Can be any processor-supported kind.

    integer(IK)                     :: i, j

    type(display_type)              :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Return the optional value if present, otherwise the default value.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    Optional_SK = reshape(["AAA", "BBB", "CCC", "DDD", "EEE", "FFF"], shape = [2,3])
    Optional_IK = reshape([1_IK, 2_IK, 3_IK, 4_IK, 5_IK, 6_IK], shape = [2,3])
    Optional_RK = reshape([1._RK, 2._RK, 3._RK, 4._RK, 5._RK, 6._RK], shape = [2,3])
    Optional_CK = reshape([(1._CK, -1._CK), (2._CK, -2._CK), (3._CK, -3._CK), (4._CK, -4._CK), (5._CK, -5._CK), (6._CK, -6._CK)], shape = [2,3])
    Optional_LK = reshape([.false._LK, .true._LK, .false._LK, .true._LK, .false._LK, .true._LK], shape = [2,3])

    Default_SK  = reshape([((Optional_SK(i,j), i = size(Optional_SK,1), 1, -1), j = size(Optional_SK,2), 1, -1)], shape = shape(Optional_SK))
    Default_IK  = reshape([((Optional_IK(i,j), i = size(Optional_IK,1), 1, -1), j = size(Optional_IK,2), 1, -1)], shape = shape(Optional_IK))
    Default_RK  = reshape([((Optional_RK(i,j), i = size(Optional_RK,1), 1, -1), j = size(Optional_RK,2), 1, -1)], shape = shape(Optional_RK))
    Default_CK  = reshape([((Optional_CK(i,j), i = size(Optional_CK,1), 1, -1), j = size(Optional_CK,2), 1, -1)], shape = shape(Optional_CK))
    Default_LK  = reshape([((Optional_LK(i,j), i = size(Optional_LK,1), 1, -1), j = size(Optional_LK,2), 1, -1)], shape = shape(Optional_LK))

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Option character scalar/array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    allocate(Output_SK, mold = Optional_SK)

    call disp%skip()
    call disp%show("Default_SK")
    call disp%show( Default_SK, deliml = SK_"""" )
    call disp%show("Optional_SK")
    call disp%show( Optional_SK, deliml = SK_"""" )
    call disp%show("Output_SK(:,:) = getOption(Default_SK)")
                    Output_SK(:,:) = getOption(Default_SK) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(:,:)")
    call disp%show( Output_SK(:,:), deliml = SK_"""" )
    call disp%show("Output_SK(:,:) = getOption(Default_SK, Optional_SK)")
                    Output_SK(:,:) = getOption(Default_SK, Optional_SK) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(:,:)")
    call disp%show( Output_SK(:,:), deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_SK(:,1)")
    call disp%show( Default_SK(:,1), deliml = SK_"""" )
    call disp%show("Optional_SK(:,1)")
    call disp%show( Optional_SK(:,1), deliml = SK_"""" )
    call disp%show("Output_SK(:,1) = getOption(Default_SK(:,1))")
                    Output_SK(:,1) = getOption(Default_SK(:,1)) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(:,1)")
    call disp%show( Output_SK(:,1), deliml = SK_"""" )
    call disp%show("Output_SK(:,1) = getOption(Default_SK(:,1), Optional_SK(:,1))")
                    Output_SK(:,1) = getOption(Default_SK(:,1), Optional_SK(:,1)) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(:,1)")
    call disp%show( Output_SK(:,1), deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_SK(1,1)")
    call disp%show( Default_SK(1,1), deliml = SK_"""" )
    call disp%show("Optional_SK(1,1)")
    call disp%show( Optional_SK(1,1), deliml = SK_"""" )
    call disp%show("Output_SK(1,1) = getOption(Default_SK(1,1))")
                    Output_SK(1,1) = getOption(Default_SK(1,1)) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(1,1)")
    call disp%show( Output_SK(1,1), deliml = SK_"""" )
    call disp%show("Output_SK(1,1) = getOption(Default_SK(1,1), Optional_SK(1,1))")
                    Output_SK(1,1) = getOption(Default_SK(1,1), Optional_SK(1,1)) ! bypass gfortran 10.3 bug
    call disp%show("Output_SK(1,1)")
    call disp%show( Output_SK(1,1), deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Option logical scalar/array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%skip()
    call disp%show("Default_LK")
    call disp%show( Default_LK )
    call disp%show("Optional_LK")
    call disp%show( Optional_LK )
    call disp%show("getOption(Default_LK)")
    call disp%show( getOption(Default_LK) )
    call disp%show("getOption(Default_LK, Optional_LK)")
    call disp%show( getOption(Default_LK, Optional_LK) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_LK(:,1)")
    call disp%show( Default_LK(:,1) )
    call disp%show("Optional_LK(:,1)")
    call disp%show( Optional_LK(:,1) )
    call disp%show("getOption(Default_LK(:,1))")
    call disp%show( getOption(Default_LK(:,1)) )
    call disp%show("getOption(Default_LK(:,1), Optional_LK(:,1))")
    call disp%show( getOption(Default_LK(:,1), Optional_LK(:,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_LK(1,:)")
    call disp%show( Default_LK(1,:) )
    call disp%show("Optional_LK(1,:)")
    call disp%show( Optional_LK(1,:) )
    call disp%show("getOption(Default_LK(1,:))")
    call disp%show( getOption(Default_LK(1,:)) )
    call disp%show("getOption(Default_LK(1,:), Optional_LK(1,:))")
    call disp%show( getOption(Default_LK(1,:), Optional_LK(1,:)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_LK(1,1)")
    call disp%show( Default_LK(1,1) )
    call disp%show("Optional_LK(1,1)")
    call disp%show( Optional_LK(1,1) )
    call disp%show("getOption(Default_LK(1,1))")
    call disp%show( getOption(Default_LK(1,1)) )
    call disp%show("getOption(Default_LK(1,1), Optional_LK(1,1))")
    call disp%show( getOption(Default_LK(1,1), Optional_LK(1,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Option integer scalar/array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%skip()
    call disp%show("Default_IK")
    call disp%show( Default_IK )
    call disp%show("Optional_IK")
    call disp%show( Optional_IK )
    call disp%show("getOption(Default_IK)")
    call disp%show( getOption(Default_IK) )
    call disp%show("getOption(Default_IK, Optional_IK)")
    call disp%show( getOption(Default_IK, Optional_IK) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_IK(:,1)")
    call disp%show( Default_IK(:,1) )
    call disp%show("Optional_IK(:,1)")
    call disp%show( Optional_IK(:,1) )
    call disp%show("getOption(Default_IK(:,1))")
    call disp%show( getOption(Default_IK(:,1)) )
    call disp%show("getOption(Default_IK(:,1), Optional_IK(:,1))")
    call disp%show( getOption(Default_IK(:,1), Optional_IK(:,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_IK(1,:)")
    call disp%show( Default_IK(1,:) )
    call disp%show("Optional_IK(1,:)")
    call disp%show( Optional_IK(1,:) )
    call disp%show("getOption(Default_IK(1,:))")
    call disp%show( getOption(Default_IK(1,:)) )
    call disp%show("getOption(Default_IK(1,:), Optional_IK(1,:))")
    call disp%show( getOption(Default_IK(1,:), Optional_IK(1,:)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_IK(1,1)")
    call disp%show( Default_IK(1,1) )
    call disp%show("Optional_IK(1,1)")
    call disp%show( Optional_IK(1,1) )
    call disp%show("getOption(Default_IK(1,1))")
    call disp%show( getOption(Default_IK(1,1)) )
    call disp%show("getOption(Default_IK(1,1), Optional_IK(1,1))")
    call disp%show( getOption(Default_IK(1,1), Optional_IK(1,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Option complex scalar/array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%skip()
    call disp%show("Default_CK")
    call disp%show( Default_CK )
    call disp%show("Optional_CK")
    call disp%show( Optional_CK )
    call disp%show("getOption(Default_CK)")
    call disp%show( getOption(Default_CK) )
    call disp%show("getOption(Default_CK, Optional_CK)")
    call disp%show( getOption(Default_CK, Optional_CK) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_CK(:,1)")
    call disp%show( Default_CK(:,1) )
    call disp%show("Optional_CK(:,1)")
    call disp%show( Optional_CK(:,1) )
    call disp%show("getOption(Default_CK(:,1))")
    call disp%show( getOption(Default_CK(:,1)) )
    call disp%show("getOption(Default_CK(:,1), Optional_CK(:,1))")
    call disp%show( getOption(Default_CK(:,1), Optional_CK(:,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_CK(1,:)")
    call disp%show( Default_CK(1,:) )
    call disp%show("Optional_CK(1,:)")
    call disp%show( Optional_CK(1,:) )
    call disp%show("getOption(Default_CK(1,:))")
    call disp%show( getOption(Default_CK(1,:)) )
    call disp%show("getOption(Default_CK(1,:), Optional_CK(1,:))")
    call disp%show( getOption(Default_CK(1,:), Optional_CK(1,:)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_CK(1,1)")
    call disp%show( Default_CK(1,1) )
    call disp%show("Optional_CK(1,1)")
    call disp%show( Optional_CK(1,1) )
    call disp%show("getOption(Default_CK(1,1))")
    call disp%show( getOption(Default_CK(1,1)) )
    call disp%show("getOption(Default_CK(1,1), Optional_CK(1,1))")
    call disp%show( getOption(Default_CK(1,1), Optional_CK(1,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("! Option real scalar/array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%skip()
    call disp%show("Default_RK")
    call disp%show( Default_RK )
    call disp%show("Optional_RK")
    call disp%show( Optional_RK )
    call disp%show("getOption(Default_RK)")
    call disp%show( getOption(Default_RK) )
    call disp%show("getOption(Default_RK, Optional_RK)")
    call disp%show( getOption(Default_RK, Optional_RK) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_RK(:,1)")
    call disp%show( Default_RK(:,1) )
    call disp%show("Optional_RK(:,1)")
    call disp%show( Optional_RK(:,1) )
    call disp%show("getOption(Default_RK(:,1))")
    call disp%show( getOption(Default_RK(:,1)) )
    call disp%show("getOption(Default_RK(:,1), Optional_RK(:,1))")
    call disp%show( getOption(Default_RK(:,1), Optional_RK(:,1)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_RK(1,:)")
    call disp%show( Default_RK(1,:) )
    call disp%show("Optional_RK(1,:)")
    call disp%show( Optional_RK(1,:) )
    call disp%show("getOption(Default_RK(1,:))")
    call disp%show( getOption(Default_RK(1,:)) )
    call disp%show("getOption(Default_RK(1,:), Optional_RK(1,:))")
    call disp%show( getOption(Default_RK(1,:), Optional_RK(1,:)) )
    call disp%skip()

    call disp%skip()
    call disp%show("Default_RK(1,1)")
    call disp%show( Default_RK(1,1) )
    call disp%show("Optional_RK(1,1)")
    call disp%show( Optional_RK(1,1) )
    call disp%show("getOption(Default_RK(1,1))")
    call disp%show( getOption(Default_RK(1,1)) )
    call disp%show("getOption(Default_RK(1,1), Optional_RK(1,1))")
    call disp%show( getOption(Default_RK(1,1), Optional_RK(1,1)) )
    call disp%skip()

end program example