program example

    use pm_kind, only: SK, IK, LK, RK
    use pm_kind, only: TKC => RKS ! All other real types are also supported.
    use pm_io, only: display_type
    use pm_sampleVar, only: getVar
    use pm_sampleMean, only: getMean
    use pm_sampleVar, only: setVarMean
    use pm_arraySpace, only: getLinSpace
    use pm_sampleCov, only: fweight, rweight
    use pm_sampleShift, only: getShifted
    use pm_arrayResize, only: setResized
    use pm_distUnif, only: getUnifRand

    implicit none

    integer(IK) :: dim
    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 1-D sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC) :: var, mean
        real(TKC), allocatable :: sample(:)
        call disp%show("sample = getLinSpace(1._TKC, 9._TKC, 5_IK)")
                        sample = getLinSpace(1._TKC, 9._TKC, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setVarMean(var, mean, sample, meang = sample(1))")
                        call setVarMean(var, mean, sample, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample) ! for comparison.")
        call disp%show( getMean(sample) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample) ! for comparison.")
        call disp%show( getVar(sample) )
        call disp%show("call setVarMean(var, mean, sample, dim = 1_IK, meang = sample(1))")
                        call setVarMean(var, mean, sample, dim = 1_IK, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, dim = 1_IK) ! for comparison.")
        call disp%show( getMean(sample, dim = 1_IK) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, dim = 1_IK) ! for comparison.")
        call disp%show( getVar(sample, dim = 1_IK) )
        call disp%skip()
    end block

    block
        real(TKC) :: var
        complex(TKC) :: mean
        complex(TKC), allocatable :: sample(:)
        call disp%show("sample = cmplx(getLinSpace(1., 9., 5_IK), -getLinSpace(1., 9., 5_IK), TKC)")
                        sample = cmplx(getLinSpace(1., 9., 5_IK), -getLinSpace(1., 9., 5_IK), TKC)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setVarMean(var, mean, sample, meang = sample(1))")
                        call setVarMean(var, mean, sample, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample) ! for comparison.")
        call disp%show( getMean(sample) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample) ! for comparison.")
        call disp%show( getVar(sample) )
        call disp%show("call setVarMean(var, mean, sample, dim = 1_IK, meang = sample(1))")
                        call setVarMean(var, mean, sample, dim = 1_IK, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, dim = 1_IK) ! for comparison.")
        call disp%show( getMean(sample, dim = 1_IK) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, dim = 1_IK) ! for comparison.")
        call disp%show( getVar(sample, dim = 1_IK) )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 1-D weighted sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC) :: var, weisum
        real(TKC), allocatable :: weight(:)
        real(TKC), allocatable :: sample(:)
        real(TKC) :: mean
        call disp%show("sample = getLinSpace(1._TKC, 9._TKC, 5_IK)")
                        sample = getLinSpace(1._TKC, 9._TKC, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))")
                        weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))
        call disp%show("weight")
        call disp%show( weight )
        call disp%show("call setVarMean(var, mean, sample, weight, weisum, meang = sample(1))")
                        call setVarMean(var, mean, sample, weight, weisum, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, weight) ! for comparison.")
        call disp%show( getMean(sample, weight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, weight) ! for comparison.")
        call disp%show( getVar(sample, weight) )
        call disp%show("call setVarMean(var, mean, sample, 1_IK, weight, weisum, meang = sample(1))")
                        call setVarMean(var, mean, sample, 1_IK, weight, weisum, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, 1_IK, weight) ! for comparison.")
        call disp%show( getMean(sample, 1_IK, weight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, 1_IK, weight) ! for comparison.")
        call disp%show( getVar(sample, 1_IK, weight) )
        call disp%skip()
    end block

    block
        real(TKC) :: var, weisum
        real(TKC), allocatable :: weight(:)
        complex(TKC), allocatable :: sample(:)
        complex(TKC) :: mean
        call disp%show("sample = cmplx(getLinSpace(1., 9., 5_IK), -getLinSpace(1., 9., 5_IK), TKC)")
                        sample = cmplx(getLinSpace(1., 9., 5_IK), -getLinSpace(1., 9., 5_IK), TKC)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))")
                        weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))
        call disp%show("weight")
        call disp%show( weight )
        call disp%show("call setVarMean(var, mean, sample, weight, weisum, meang = sample(1))")
                        call setVarMean(var, mean, sample, weight, weisum, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, weight) ! for comparison.")
        call disp%show( getMean(sample, weight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, weight) ! for comparison.")
        call disp%show( getVar(sample, weight) )
        call disp%show("call setVarMean(var, mean, sample, 1_IK, weight, weisum, meang = sample(1))")
                        call setVarMean(var, mean, sample, 1_IK, weight, weisum, meang = sample(1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, 1_IK, weight) ! for comparison.")
        call disp%show( getMean(sample, 1_IK, weight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, 1_IK, weight) ! for comparison.")
        call disp%show( getVar(sample, 1_IK, weight) )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 2-D array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC), allocatable :: var(:)
        real(TKC), allocatable :: meang(:), mean(:), sample(:,:)
        call disp%skip()
        call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                        sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("call setResized(mean, 1_IK)")
                        call setResized(mean, 1_IK)
        call disp%show("call setVarMean(var(1), mean(1), sample, meang = sample(1,1))")
                        call setVarMean(var(1), mean(1), sample, meang = sample(1,1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample) ! for comparison.")
        call disp%show( getMean(sample) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample) ! for comparison.")
        call disp%show( getVar(sample) )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                            sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
            call disp%show("sample")
            call disp%show( sample )
            call disp%show("call setResized(var, size(sample, 3 - dim, IK))")
                            call setResized(var, size(sample, 3 - dim, IK))
            call disp%show("call setResized(mean, size(sample, 3 - dim, IK))")
                            call setResized(mean, size(sample, 3 - dim, IK))
            call disp%show("if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if")
                            if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if
            call disp%show("call setVarMean(var, mean, sample, dim, meang)")
                            call setVarMean(var, mean, sample, dim, meang)
            call disp%show("mean")
            call disp%show( mean )
            call disp%show("getMean(sample, dim) ! for comparison.")
            call disp%show( getMean(sample, dim) )
            call disp%show("var")
            call disp%show( var )
            call disp%show("getVar(sample, dim) ! for comparison.")
            call disp%show( getVar(sample, dim) )
            call disp%skip()
        end do
    end block

    block
        real(TKC), allocatable :: var(:)
        complex(TKC), allocatable :: meang(:), mean(:), sample(:,:)
        call disp%skip()
        call disp%show("sample = cmplx(getUnifRand(1., 9., 4_IK, 5_IK), -getUnifRand(1., 9., 4_IK, 5_IK), TKC)")
                        sample = cmplx(getUnifRand(1., 9., 4_IK, 5_IK), -getUnifRand(1., 9., 4_IK, 5_IK), TKC)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("call setResized(mean, 1_IK)")
                        call setResized(mean, 1_IK)
        call disp%show("call setVarMean(var(1), mean(1), sample, meang = sample(1,1))")
                        call setVarMean(var(1), mean(1), sample, meang = sample(1,1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample) ! for comparison.")
        call disp%show( getMean(sample) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample) ! for comparison.")
        call disp%show( getVar(sample) )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = cmplx(getUnifRand(1., 9., 4_IK, 5_IK), -getUnifRand(1., 9., 4_IK, 5_IK), TKC)")
                            sample = cmplx(getUnifRand(1., 9., 4_IK, 5_IK), -getUnifRand(1., 9., 4_IK, 5_IK), TKC)
            call disp%show("sample")
            call disp%show( sample )
            call disp%show("call setResized(var, size(sample, 3 - dim, IK))")
                            call setResized(var, size(sample, 3 - dim, IK))
            call disp%show("call setResized(mean, size(sample, 3 - dim, IK))")
                            call setResized(mean, size(sample, 3 - dim, IK))
            call disp%show("if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if")
                            if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if
            call disp%show("call setVarMean(var, mean, sample, dim, meang)")
                            call setVarMean(var, mean, sample, dim, meang)
            call disp%show("mean")
            call disp%show( mean )
            call disp%show("getMean(sample, dim) ! for comparison.")
            call disp%show( getMean(sample, dim) )
            call disp%show("var")
            call disp%show( var )
            call disp%show("getVar(sample, dim) ! for comparison.")
            call disp%show( getVar(sample, dim) )
            call disp%skip()
        end do
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 2-D weighted sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC):: rweisum
        real(TKC), allocatable :: var(:)
        real(TKC), allocatable :: rweight(:)
        real(TKC), allocatable :: meang(:), mean(:), sample(:,:)
        integer(IK), allocatable :: iweight(:)
        integer(IK) :: iweisum
        call disp%skip()
        call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                        sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("iweight = getUnifRand(1, 9, size(sample, kind = IK))")
                        iweight = getUnifRand(1, 9, size(sample, kind = IK))
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("rweight = iweight")
                        rweight = iweight
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("call setResized(mean, 1_IK)")
                        call setResized(mean, 1_IK)
        call disp%show("call setVarMean(var(1), mean(1), sample, iweight, iweisum, meang = sample(1,1))")
                        call setVarMean(var(1), mean(1), sample, iweight, iweisum, meang = sample(1,1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, iweight) ! for comparison.")
        call disp%show( getMean(sample, iweight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, iweight) ! for comparison.")
        call disp%show( getVar(sample, iweight) )
        call disp%show("[iweisum, sum(iweight)] ! for comparison.")
        call disp%show( [iweisum, sum(iweight)] )
        call disp%show("call setVarMean(var(1), mean(1), sample, rweight, rweisum, meang = sample(1,1))")
                        call setVarMean(var(1), mean(1), sample, rweight, rweisum, meang = sample(1,1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("getMean(sample, rweight) ! for comparison.")
        call disp%show( getMean(sample, rweight) )
        call disp%show("var")
        call disp%show( var )
        call disp%show("getVar(sample, rweight) ! for comparison.")
        call disp%show( getVar(sample, rweight) )
        call disp%show("[rweisum, sum(rweight)] ! for comparison.")
        call disp%show( [rweisum, sum(rweight)] )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                            sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
            call disp%show("sample")
            call disp%show( sample )
            call disp%show("iweight = getUnifRand(1, 9, size(sample, dim, IK))")
                            iweight = getUnifRand(1, 9, size(sample, dim, IK))
            call disp%show("iweight")
            call disp%show( iweight )
            call disp%show("call setResized(var, size(sample, 3 - dim, IK))")
                            call setResized(var, size(sample, 3 - dim, IK))
            call disp%show("call setResized(mean, size(sample, 3 - dim, IK))")
                            call setResized(mean, size(sample, 3 - dim, IK))
            call disp%show("if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if")
                            if (dim == 1) then; meang = sample(1,:); else; meang = sample(:,1); end if
            call disp%show("call setVarMean(var, mean, sample, dim, iweight, iweisum, meang)")
                            call setVarMean(var, mean, sample, dim, iweight, iweisum, meang)
            call disp%show("mean")
            call disp%show( mean )
            call disp%show("getMean(sample, dim, iweight) ! for comparison.")
            call disp%show( getMean(sample, dim, iweight) )
            call disp%show("var")
            call disp%show( var )
            call disp%show("getVar(sample, dim, iweight) ! for comparison.")
            call disp%show( getVar(sample, dim, iweight) )
            call disp%show("[iweisum, sum(iweight)] ! for comparison.")
            call disp%show( [iweisum, sum(iweight)] )
            call disp%skip()
        end do
    end block

end program example