program example

    use pm_kind, only: SK, IK, LK
    use pm_sampleShift, only: getShifted
    use pm_arraySpace, only: getLinSpace
    use pm_arrayResize, only: setResized
    use pm_distUnif, only: getUnifRand
    use pm_arrayFill, only: getFilled
    use pm_sampleCov, only: uppDia
    use pm_sampleCov, only: lowDia
    use pm_sampleCov, only: setCovMean
    use pm_io, only: display_type
    use pm_io, only: getFormat

    implicit none

    integer(IK) :: itry, ntry = 10
    type(display_type) :: disp
    character(:), allocatable :: format
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the covariance matrix of a 2-D sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! All other real types are also supported, e.g., RK32, RK64, RK128.
        real(TKC), allocatable :: sample(:,:), cov(:,:), mean(:), meang(:)
        integer(IK) :: ndim, nsam, dim
        call disp%show("ndim = 2; nsam = 10; dim = 2")
                        ndim = 2; nsam = 10; dim = 2
        call disp%show("sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])")
                        sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("meang = sample(:,1)")
                        meang = sample(:,1)
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, sample, dim, meang)")
                        call setCovMean(cov, uppDia, mean, sample, dim, meang)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, sample, dim, meang)")
                        call setCovMean(cov, lowDia, mean, sample, dim, meang)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, transpose(sample), dim, meang)")
                        call setCovMean(cov, uppDia, mean, transpose(sample), dim, meang)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, transpose(sample), dim, meang)")
                        call setCovMean(cov, lowDia, mean, transpose(sample), dim, meang)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, mean, sample(1,:), sample(2,:), meang = sample(1:2,1))")
                        call setCovMean(cov, mean, sample(1,:), sample(2,:), meang = sample(1:2,1))
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the biased covariance matrix of a weighted 2-D sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! All other real types are also supported, e.g., RK32, RK64, RK128.
        real(TKC) :: rweisum
        integer(IK) :: iweisum
        real(TKC), allocatable :: rweight(:)
        integer(IK), allocatable :: iweight(:)
        real(TKC), allocatable :: sample(:,:), cov(:,:), mean(:), meang(:)
        integer(IK) :: ndim, nsam, dim
        call disp%show("ndim = 2; nsam = 10; dim = 2")
                        ndim = 2; nsam = 10; dim = 2
        call disp%show("sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])")
                        sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("meang = sample(:,1)")
                        meang = sample(:,1)
        call disp%show("call setResized(mean, ndim)")
                        call setResized(mean, ndim)
        call disp%show("iweight = getUnifRand(1, 10, nsam) ! integer-valued weights.")
                        iweight = getUnifRand(1, 10, nsam) ! integer-valued weights.
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("rweight = iweight ! or real-valued weights.")
                        rweight = iweight ! or real-valued weights.
        call disp%show("iweight")
        call disp%show( iweight )

        call disp%skip()
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%show("!Compute the covariance matrix integer weights.")
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%skip()

        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, sample, dim, iweight, iweisum, meang)")
                        call setCovMean(cov, uppDia, mean, sample, dim, iweight, iweisum, meang)
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, sample, dim, iweight, iweisum, meang)")
                        call setCovMean(cov, lowDia, mean, sample, dim, iweight, iweisum, meang)
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, transpose(sample), dim, iweight, iweisum, meang)")
                        call setCovMean(cov, uppDia, mean, transpose(sample), dim, iweight, iweisum, meang)
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, transpose(sample), dim, iweight, iweisum, meang)")
                        call setCovMean(cov, lowDia, mean, transpose(sample), dim, iweight, iweisum, meang)
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, mean, sample(1,:), sample(2,:), iweight, iweisum, meang = sample(1:2,1))")
                        call setCovMean(cov, mean, sample(1,:), sample(2,:), iweight, iweisum, meang = sample(1:2,1))
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()

        call disp%skip()
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%show("!Compute the covariance matrix    real weights.")
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%skip()

        call disp%show("dim = 2_IK")
                        dim = 2_IK
        call disp%show("meang = sample(:,1)")
                        meang = sample(:,1)
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, sample, dim, rweight, rweisum, meang)")
                        call setCovMean(cov, uppDia, mean, sample, dim, rweight, rweisum, meang)
        call disp%show("rweisum")
        call disp%show( rweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, sample, dim, rweight, rweisum, meang)")
                        call setCovMean(cov, lowDia, mean, sample, dim, rweight, rweisum, meang)
        call disp%show("rweisum")
        call disp%show( rweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, uppDia, mean, transpose(sample), dim, rweight, rweisum, meang)")
                        call setCovMean(cov, uppDia, mean, transpose(sample), dim, rweight, rweisum, meang)
        call disp%show("rweisum")
        call disp%show( rweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, lowDia, mean, transpose(sample), dim, rweight, rweisum, meang)")
                        call setCovMean(cov, lowDia, mean, transpose(sample), dim, rweight, rweisum, meang)
        call disp%show("rweisum")
        call disp%show( rweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("mean = getFilled(0., ndim)")
                        mean = getFilled(0., ndim)
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCovMean(cov, mean, sample(1,:), sample(2,:), rweight, rweisum, meang = sample(1:2,1))")
                        call setCovMean(cov, mean, sample(1,:), sample(2,:), rweight, rweisum, meang = sample(1:2,1))
        call disp%show("rweisum")
        call disp%show( rweisum )
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
    end block

end program example