function delFile(self, file, desc)
    if nargin<3; desc = "the requested file"; end
    try
        delete(file);
    catch
        warning ( newline ...
                + "Failed to delete " + string(desc) + " from the local disk. File may be protected. You can try manually deleting it: " + newline ...
                + newline ...
                + "    " + string(file) + newline ...
                + newline ...
                );
    end
end