classdef SpecMCMC_RandomStartPointRequested_class < handle

    properties (Constant)
        CLASS_NAME  = "@SpecMCMC_RandomStartPointRequested_class"
    end

    properties
        val         = []
        def         = []
        desc        = []
    end

%***********************************************************************************************************************************
%***********************************************************************************************************************************

    methods (Access = public)

    %*******************************************************************************************************************************
    %*******************************************************************************************************************************

        function self = SpecMCMC_RandomStartPointRequested_class(methodName)
            self.def    = false;
            self.desc   = "If randomStartPointRequested=TRUE (or true or t, all case-insensitive), then the StartPoint will be initialized randomly "   ...
                        + "for each MCMC chain that is to be generated by " + methodName + ". The random values will be drawn from the specified "      ...
                        + "or the default domain of StartPoint, given by RandomStartPointDomain variable. Note that the value of StartPoint, if "       ...
                        + "provided, has precedence over random initialization. In other words, for every element of StartPoint that is not provided "  ...
                        + "as input only that element will initialized randomly if randomStartPointRequested=TRUE. "                                    ...
                        + "Also, note that even if StartPoint is randomly initialized, its random value will be deterministic between different "       ...
                        + "independent runs of " + methodName + " if the input variable randomSeed is provided by the user. "                           ...
                        + "The default value is " + self.def + "."                                                                                      ...
                        ;
        end

    %*******************************************************************************************************************************
    %*******************************************************************************************************************************

        function set(self, randomStartPointRequested)
            if isempty(randomStartPointRequested)
                self.val = self.def;
            else
                self.val = randomStartPointRequested;
            end
        end

    %*******************************************************************************************************************************
    %*******************************************************************************************************************************

    end

%***********************************************************************************************************************************
%***********************************************************************************************************************************

end