program example

    use pm_kind, only: SK, IK, LK
    use pm_kind, only: RKC => RKH ! all processor kinds are supported.
    use pm_mathRoot, only: getRoot, false, bisection, secant, brent, ridders, toms748, newton, halley, schroder
    use pm_io, only: display_type

    implicit none

    real(RKC) :: root
    integer(IK) :: neval
    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("root = getRoot(getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(false, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(false, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(bisection, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(bisection, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(secant, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(secant, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(brent, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(brent, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(ridders, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(ridders, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(toms748, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(toms748, getSin, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(newton, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(newton, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(halley, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(halley, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(schroder, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(schroder, getSinDiff, lb = 2._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getSin(root)]")
    call disp%show( [root, getSin(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()



    call disp%skip()
    call disp%show("root = getRoot(getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(false, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(false, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(bisection, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(bisection, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(secant, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(secant, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(brent, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(brent, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(ridders, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(ridders, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(toms748, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(toms748, getCos, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(newton, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(newton, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(halley, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(halley, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(schroder, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)")
                    root = getRoot(schroder, getCosDiff, lb = 1._RKC, ub = 3._RKC, neval = neval)
    call disp%show("[root, getCos(root)]")
    call disp%show( [root, getCos(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()



    call disp%skip()
    call disp%show("root = getRoot(getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(false, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(false, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(bisection, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(bisection, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(secant, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(secant, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(brent, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(brent, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(ridders, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(ridders, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(toms748, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(toms748, getQuad, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(newton, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(newton, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(halley, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(halley, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()
    call disp%show("root = getRoot(schroder, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)")
                    root = getRoot(schroder, getQuadDiff, lb = -1._RKC, ub = 4._RKC, neval = neval)
    call disp%show("[root, getQuad(root)]")
    call disp%show( [root, getQuad(root)] )
    call disp%show("neval")
    call disp%show( neval )
    call disp%skip()

contains

    pure function getSin(x) result(func)
        real(RKC), intent(in) :: x
        real(RKC) :: func
        func = sin(x)
    end function

    pure function getCos(x) result(func)
        real(RKC), intent(in) :: x
        real(RKC) :: func
        func = cos(x)
    end function

    pure function getQuad(x) result(func)
        real(RKC), intent(in) :: x
        real(RKC) :: func
        func = x * (x - 1._RKC) * (x - 2._RKC)
    end function

    pure function getSinDiff(x, order) result(func)
        integer(IK), intent(in) :: order
        real(RKC), intent(in) :: x
        real(RKC) :: func
        if (order == 0) func = +getSin(x)
        if (order == 1) func = +cos(x)
        if (order == 2) func = -sin(x)
    end function

    pure function getCosDiff(x, order) result(func)
        integer(IK), intent(in) :: order
        real(RKC), intent(in) :: x
        real(RKC) :: func
        if (order == 0) func = +getCos(x)
        if (order == 1) func = -sin(x)
        if (order == 2) func = -cos(x)
    end function

    pure function getQuadDiff(x, order) result(func)
        integer(IK), intent(in) :: order
        real(RKC), intent(in) :: x
        real(RKC) :: func
        if (order == 0) func = getQuad(x)
        if (order == 1) func = 3._RKC * x**2 - 6._RKC * x + 2._RKC
        if (order == 2) func = 6._RKC * x - 6._RKC
    end function

end program example