program example

    use pm_kind, only: SK, IK, LK ! all intrinsic types and kinds are supported.
    use pm_arraySort, only: isDescending
    use pm_io, only: display_type

    implicit none

    type(display_type) :: disp

    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("isDescending('')")
    call disp%show( isDescending('') )
    call disp%skip()
    call disp%show("isDescending('?Aa')")
    call disp%show( isDescending('?Aa') )
    call disp%skip()
    call disp%show("isDescending('A!b')")
    call disp%show( isDescending('A!b') )
    call disp%skip()
    call disp%show("isDescending('zxw')")
    call disp%show( isDescending('zxw') )
    call disp%skip()
    call disp%show("isDescending('AAA')")
    call disp%show( isDescending('AAA') )
    call disp%skip()

    call disp%skip()
    call disp%show("isDescending([character(0) ::])")
    call disp%show( isDescending([character(0) ::]) )
    call disp%skip()
    call disp%show("isDescending(['?', 'A', 'a'])")
    call disp%show( isDescending(['?', 'A', 'a']) )
    call disp%skip()
    call disp%show("isDescending(['A', '!', 'b'])")
    call disp%show( isDescending(['A', '!', 'b']) )
    call disp%skip()
    call disp%show("isDescending(['z', 'x', 'w'])")
    call disp%show( isDescending(['z', 'x', 'w']) )
    call disp%skip()
    call disp%show("isDescending(['A', 'A', 'A'])")
    call disp%show( isDescending(['A', 'A', 'A']) )
    call disp%skip()

    call disp%skip()
    call disp%show("isDescending([integer ::])")
    call disp%show( isDescending([integer ::]) )
    call disp%skip()
    call disp%show("isDescending([+1, +2, +3])")
    call disp%show( isDescending([+1, +2, +3]) )
    call disp%skip()
    call disp%show("isDescending([-1, -2, -3])")
    call disp%show( isDescending([-1, -2, -3]) )
    call disp%skip()
    call disp%show("isDescending([-1, +2, -3])")
    call disp%show( isDescending([-1, +2, -3]) )
    call disp%skip()
    call disp%show("isDescending([-1, -1, -1])")
    call disp%show( isDescending([-1, -1, -1]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isDescending([logical ::])")
    call disp%show( isDescending([logical ::]) )
    call disp%skip()
    call disp%show("isDescending([.false., .false., .true.])")
    call disp%show( isDescending([.false., .false., .true.]) )
    call disp%skip()
    call disp%show("isDescending([.true., .false., .false.])")
    call disp%show( isDescending([.true., .false., .false.]) )
    call disp%skip()
    call disp%show("isDescending([.false., .true., .false.])")
    call disp%show( isDescending([.false., .true., .false.]) )
    call disp%skip()
    call disp%show("isDescending([.true., .true., .true.])")
    call disp%show( isDescending([.true., .true., .true.]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isDescending([complex ::])")
    call disp%show( isDescending([complex ::]) )
    call disp%skip()
    call disp%show("isDescending([(+1., -1.), (+2., -2.), (+3., -3.)])")
    call disp%show( isDescending([(+1., -1.), (+2., -2.), (+3., -3.)]) )
    call disp%skip()
    call disp%show("isDescending([(-1., +1.), (-2., +2.), (-3., +3.)])")
    call disp%show( isDescending([(-1., +1.), (-2., +2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isDescending([(-1., +1.), (+2., -2.), (-3., +3.)])")
    call disp%show( isDescending([(-1., +1.), (+2., -2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isDescending([(-1., +1.), (-1., +1.), (-1., +1.)])")
    call disp%show( isDescending([(-1., +1.), (-1., +1.), (-1., +1.)]) )
    call disp%skip()
    call disp%show("isDescending([(-1., +1.), (-1., -2.), (-1., +3.)])")
    call disp%show( isDescending([(-1., +1.), (-1., -2.), (-1., +3.)]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isDescending([real ::])")
    call disp%show( isDescending([real ::]) )
    call disp%skip()
    call disp%show("isDescending([+1., +2., +3.])")
    call disp%show( isDescending([+1., +2., +3.]) )
    call disp%skip()
    call disp%show("isDescending([-1., -2., -3.])")
    call disp%show( isDescending([-1., -2., -3.]) )
    call disp%skip()
    call disp%show("isDescending([-1., +2., -3.])")
    call disp%show( isDescending([-1., +2., -3.]) )
    call disp%skip()
    call disp%show("isDescending([-1., -1., -1.])")
    call disp%show( isDescending([-1., -1., -1.]) )
    call disp%skip()

#if PDT_ENABLED
    !   \bug
    !   Intel ifort 2022.3 cannot handle aliases for pdt names (e.g., strc => css_pdt).
    block
        use pm_container, only: css_pdt
        call disp%skip()
        call disp%show("isDescending([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')])")
        call disp%show( isDescending([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')]) )
        call disp%skip()
        call disp%show("isDescending([css_pdt('string'), css_pdt('is'), css_pdt('sorted')])")
        call disp%show( isDescending([css_pdt('string'), css_pdt('is'), css_pdt('sorted')]) )
        call disp%skip()
        call disp%show("isDescending([css_pdt('same string'), css_pdt('same '), css_pdt('same')])")
        call disp%show( isDescending([css_pdt('same string'), css_pdt('same '), css_pdt('same')]) )
        call disp%skip()
    end block
#endif

end program example