program example

    use pm_kind, only: SK, IK, LK
    use pm_kind, only: CKG => CKS ! all processor real and complex kinds are supported.
    use pm_io, only: display_type
    use pm_polynomial, only: getPolyRoot, getPolyVal
    use pm_polynomial, only: eigen, jenkins, laguerre

    implicit none

    complex(CKG), allocatable :: coef(:), root(:)

    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("coef = [complex(CKG) :: -4, 1, -4, 1]")
                    coef = [complex(CKG) :: -4, 1, -4, 1]
    call disp%show("coef")
    call disp%show( coef )
    call disp%show("root = getPolyRoot(coef%re) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = eigen) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = eigen)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = jenkins) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = jenkins)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = laguerre) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = laguerre)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()

    call disp%skip()
    call disp%show("coef = [complex(CKG) :: -120, 274, -225, 85, -15, 1]")
                    coef = [complex(CKG) :: -120, 274, -225, 85, -15, 1]
    call disp%show("coef")
    call disp%show( coef )
    call disp%show("root = getPolyRoot(coef%re) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = eigen) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = eigen)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = jenkins) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = jenkins)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = laguerre) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = laguerre)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()

    call disp%skip()
    call disp%show("coef = [complex(CKG) :: 8, -8, 16, -16, 8, -8]")
                    coef = [complex(CKG) :: 8, -8, 16, -16, 8, -8]
    call disp%show("coef")
    call disp%show( coef )
    call disp%show("root = getPolyRoot(coef%re) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = eigen) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = eigen)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = jenkins) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = jenkins)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef%re, method = laguerre) ! polynomial with real coefficients.")
                    root = getPolyRoot(coef%re, method = laguerre)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()

    call disp%skip()
    call disp%show("coef = [complex(CKG) :: -120, 274, -225, 85, -15, 1]")
                    coef = [complex(CKG) :: -120, 274, -225, 85, -15, 1]
    call disp%show("coef")
    call disp%show( coef )
    call disp%show("root = getPolyRoot(coef)")
                    root = getPolyRoot(coef)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef, method = eigen)")
                    root = getPolyRoot(coef, method = eigen)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef, method = jenkins)")
                    root = getPolyRoot(coef, method = jenkins)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()
    call disp%show("root = getPolyRoot(coef, method = laguerre)")
                    root = getPolyRoot(coef, method = laguerre)
    call disp%show("root")
    call disp%show( root )
    call disp%show("getPolyVal(coef, root)")
    call disp%show( getPolyVal(coef, root) )
    call disp%skip()

end program example