clear all;
close all;

pointsFileList =    [ "../output/Test_Kmeans_mod@test_runKmeans_1@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_2@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_3@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_4@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_5@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_1@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_2@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_3@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_4@points.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_5@points.1.txt" ...
                    ];

centerFileList =    [ "../output/Test_Kmeans_mod@test_runKmeans_1@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_2@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_3@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_4@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeans_5@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_1@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_2@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_3@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_4@centers.1.txt" ...
                    , "../output/Test_Kmeans_mod@test_runKmeansOOP_5@centers.1.txt" ...
                    ];

lenFileList = length(pointsFileList);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for ifile = 1:lenFileList
    d = importdata(pointsFileList(ifile));
    c = importdata(centerFileList(ifile));
    figure(); hold on;
    ids = unique(d.data(:,end));
    for i = 1:length(ids)
        mask = d.data(:,end) == ids(i);
        plot( d.data(mask,1) ...
            , d.data(mask,2) ...
            , "." ...
            );
    end
    plot( c.data(:,1) ...
        , c.data(:,2) ...
        , "." ...
        , "color", " black" ...
        , "MarkerSize", 20 ...
        );
    hold off;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

