clear all;
close all;

d = importdata("../output/Test_Kmeans_mod@test_runKmeans_1@points.1.txt");
c = importdata("../output/Test_Kmeans_mod@test_runKmeans_1@centers.1.txt");
figure(); hold on;
ids = unique(d.data(:,end));
for i = 1:length(ids)
    mask = d.data(:,end) == ids(i);
    plot( d.data(mask,1) ...
        , d.data(mask,2) ...
        , "." ...
        );
end
plot( c.data(:,1) ...
    , c.data(:,2) ...
    , "." ...
    , "color", " black" ...
    , "MarkerSize", 20 ...
    );
hold off;

d = importdata("../output/Test_Kmeans_mod@test_runKmeans_2@points.1.txt");
c = importdata("../output/Test_Kmeans_mod@test_runKmeans_2@centers.1.txt");
figure(); hold on;
ids = unique(d.data(:,end));
for i = 1:length(ids)
    mask = d.data(:,end) == ids(i);
    plot( d.data(mask,1) ...
        , d.data(mask,2) ...
        , "." ...
        );
end
plot( c.data(:,1) ...
    , c.data(:,2) ...
    , "." ...
    , "color", " black" ...
    , "MarkerSize", 20 ...
    );
hold off;

