#!/bin/bash --login
#PBS -l mppwidth=64
#PBS -l walltime=00:10:00
#PBS -l mppnppn=16
#PBS -j oe
module load craype-hugepages2M
# change to the directory from which the job was submitted
cd $PBS_O_WORKDIR
# Get total number of processes and the number per node
#export NPROC=‘qstat -f $PBS_JOBID | awk ’/mppwidth/ {print $3}’‘
#export NTASK=‘qstat -f $PBS_JOBID | awk ’/mppnppn/ {print $3}’‘
echo "Starting job $PBS_JOBID at ‘date‘"
time aprun -n64 -N16 ./burgers_caf
#time aprun -n$NPROC -N $NTASK ./parallel_tmps
echo "Finished job $PBS_JOBID at ‘date‘"
