iaxis = 0;
axisCounter = 0;
for irow = nrow:-1:1
    for icol = ncol:-1:1
        axisCounter = axisCounter + 1;
        iaxis = (nrow-irow)*nrow + icol;
        disp( "generating plot #" + string(axisCounter) + " out of " + axisCountString )
        set( ax(iaxis)  , "position", ...
                        [ (icol-1)*(self.layout.axis.subplot.interspace + self.layout.axis.subplot.width)   + self.layout.axis.main.margin.left ...
                        , (irow-1)*(self.layout.axis.subplot.interspace + self.layout.axis.subplot.height)  + self.layout.axis.main.margin.bottom ...
                        , self.layout.axis.subplot.width ...
                        , self.layout.axis.subplot.height ...
                        ] ...
                        );
        
    end
end
