program example

    use pm_kind, only: SK, IK, LK
    use pm_kind, only: TKC => RKS ! All other real types are also supported.
    use pm_io, only: display_type
    use pm_sampleVar, only: getVar
    use pm_arraySpace, only: getLinSpace
    use pm_arrayShuffle, only: getShuffled
    use pm_sampleCov, only: fweight, rweight
    use pm_sampleShift, only: getShifted
    use pm_arrayResize, only: setResized
    use pm_distUnif, only: getUnifRand
    use pm_sampleMean, only: getMean

    implicit none

    integer(IK) :: dim
    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 1-D array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC) :: var
        real(TKC), allocatable :: sample(:)
        call disp%show("sample = getLinSpace(1._TKC, 9._TKC, 5_IK)")
                        sample = getLinSpace(1._TKC, 9._TKC, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("var = getVar(sample)")
                        var = getVar(sample)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, correction = fweight)")
                        var = getVar(sample, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, correction = rweight)")
                        var = getVar(sample, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK)")
                        var = getVar(sample, dim = 1_IK)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, correction = fweight)")
                        var = getVar(sample, dim = 1_IK, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, correction = rweight)")
                        var = getVar(sample, dim = 1_IK, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%skip()
    end block

    block
        real(TKC) :: var
        complex(TKC) , allocatable :: sample(:)
        call disp%show("sample = cmplx(getShuffled(getLinSpace(1., 9., 5_IK)), getShuffled(getLinSpace(1., 9., 5_IK)), TKC)")
                        sample = cmplx(getShuffled(getLinSpace(1., 9., 5_IK)), getShuffled(getLinSpace(1., 9., 5_IK)), TKC)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("var = getVar(sample)")
                        var = getVar(sample)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, correction = fweight)")
                        var = getVar(sample, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, correction = rweight)")
                        var = getVar(sample, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK)")
                        var = getVar(sample, dim = 1_IK)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, correction = fweight)")
                        var = getVar(sample, dim = 1_IK, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, correction = rweight)")
                        var = getVar(sample, dim = 1_IK, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 2-D array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC), allocatable :: var(:), sample(:,:)
        call disp%skip()
        call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                        sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("var(1) = getVar(sample)")
                        var(1) = getVar(sample)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, correction = fweight)")
                        var(1) = getVar(sample, correction = fweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, correction = rweight)")
                        var(1) = getVar(sample, correction = rweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                            sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
            call disp%show("var = getVar(sample, dim, correction = fweight)")
                            var = getVar(sample, dim, correction = fweight)
            call disp%show("var")
            call disp%show( var )
            call disp%show("var = getVar(sample, dim, correction = rweight)")
                            var = getVar(sample, dim, correction = rweight)
            call disp%show("var")
            call disp%show( var )
            call disp%skip()
        end do
    end block

    block
        real(TKC), allocatable :: var(:)
        complex(TKC), allocatable :: sample(:,:)
        call disp%skip()
        call disp%show("sample = cmplx(getUnifRand(-9, 9, 4_IK, 5_IK), -getUnifRand(-9, 9, 4_IK, 5_IK), TKC)")
                        sample = cmplx(getUnifRand(-9, 9, 4_IK, 5_IK), -getUnifRand(-9, 9, 4_IK, 5_IK), TKC)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("var(1) = getVar(sample)")
                        var(1) = getVar(sample)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, correction = fweight)")
                        var(1) = getVar(sample, correction = fweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, correction = rweight)")
                        var(1) = getVar(sample, correction = rweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = cmplx(getUnifRand(-9, 9, 4_IK, 5_IK), -getUnifRand(-9, 9, 4_IK, 5_IK), TKC)")
                            sample = cmplx(getUnifRand(-9, 9, 4_IK, 5_IK), -getUnifRand(-9, 9, 4_IK, 5_IK), TKC)
            call disp%show("sample")
            call disp%show( sample )
            call disp%show("var = getVar(sample, dim)")
                            var = getVar(sample, dim)
            call disp%show("var")
            call disp%show( var )
            call disp%show("var = getVar(sample, dim, correction = fweight)")
                            var = getVar(sample, dim, correction = fweight)
            call disp%show("var")
            call disp%show( var )
            call disp%show("var = getVar(sample, dim, correction = rweight)")
                            var = getVar(sample, dim, correction = rweight)
            call disp%show("var")
            call disp%show( var )
            call disp%skip()
        end do
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 1-D weighted array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC) :: var
        real(TKC), allocatable :: sample(:)
        real(TKC) , allocatable :: weight(:)
        call disp%show("sample = getLinSpace(1._TKC, 9._TKC, 5_IK)")
                        sample = getLinSpace(1._TKC, 9._TKC, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("weight = getLinSpace(1._TKC, 9._TKC, size(sample, 1, IK))")
                        weight = getLinSpace(1._TKC, 9._TKC, size(sample, 1, IK))
        call disp%show("weight")
        call disp%show( weight )
        call disp%show("var = getVar(sample, weight = weight)")
                        var = getVar(sample, weight = weight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, weight = weight, correction = fweight)")
                        var = getVar(sample, weight = weight, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, weight = weight, correction = rweight)")
                        var = getVar(sample, weight = weight, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, weight = weight)")
                        var = getVar(sample, dim = 1_IK, weight = weight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, weight = weight, correction = fweight)")
                        var = getVar(sample, dim = 1_IK, weight = weight, correction = fweight)
        call disp%show("var")
        call disp%show( var )
        call disp%show("var = getVar(sample, dim = 1_IK, weight = weight, correction = rweight)")
                        var = getVar(sample, dim = 1_IK, weight = weight, correction = rweight)
        call disp%show("var")
        call disp%show( var )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a 2-D weighted array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC), allocatable :: var(:), sample(:,:)
        real(TKC), allocatable :: weight(:)
        call disp%skip()
        call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                        sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))")
                        weight = getLinSpace(1._TKC, 9._TKC, size(sample, kind = IK))
        call disp%show("weight")
        call disp%show( weight )
        call disp%show("call setResized(var, 1_IK)")
                        call setResized(var, 1_IK)
        call disp%show("var(1) = getVar(sample, weight = weight)")
                        var(1) = getVar(sample, weight = weight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, weight = weight, correction = fweight)")
                        var(1) = getVar(sample, weight = weight, correction = fweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%show("var(1) = getVar(sample, weight = weight, correction = rweight)")
                        var(1) = getVar(sample, weight = weight, correction = rweight)
        call disp%show("var(1)")
        call disp%show( var(1) )
        call disp%skip()
        do dim = 1, 2
            call disp%show("dim ! The observations axis.")
            call disp%show( dim )
            call disp%show("sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)")
                            sample = getUnifRand(1._TKC, 9._TKC, 4_IK, 5_IK)
            call disp%show("sample")
            call disp%show( sample )
            call disp%show("weight = getLinSpace(1._TKC, 9._TKC, size(sample, dim, IK))")
                            weight = getLinSpace(1._TKC, 9._TKC, size(sample, dim, IK))
            call disp%show("weight")
            call disp%show( weight )
            call disp%show("var = getVar(sample, dim, weight = weight)")
                            var = getVar(sample, dim, weight = weight)
            call disp%show("var")
            call disp%show( var )
            call disp%show("var = getVar(sample, dim, weight = weight, correction = fweight)")
                            var = getVar(sample, dim, weight = weight, correction = fweight)
            call disp%show("var")
            call disp%show( var )
            call disp%show("var = getVar(sample, dim, weight = weight, correction = rweight)")
                            var = getVar(sample, dim, weight = weight, correction = rweight)
            call disp%show("var")
            call disp%show( var )
            call disp%skip()
        end do
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the variance of a multidimensional array by reshaping the array.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        real(TKC), allocatable :: var
        real(TKC), allocatable, target :: sample(:,:,:)
        real(TKC), pointer :: samptr(:)
        call disp%show("sample = getUnifRand(0., 1., 3_IK, 3_IK, 3_IK)")
                        sample = getUnifRand(0., 1., 3_IK, 3_IK, 3_IK)
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("samptr(1:product(shape(sample))) => sample")
                        samptr(1:product(shape(sample))) => sample
        call disp%show("var = getVar(samptr)")
                        var = getVar(samptr)
        call disp%show("var")
        call disp%show( var )
        call disp%show("nullify(samptr)")
                        nullify(samptr)
        call disp%skip()
    end block

end program example