program example

    use pm_kind, only: SK, IK, LK ! all intrinsic types and kinds are supported.
    use pm_container, only: css_pdt
    use pm_arraySort, only: isAscendingAll
    use pm_io, only: display_type

    implicit none

    type(display_type) :: disp

    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("isAscendingAll('')")
    call disp%show( isAscendingAll('') )
    call disp%skip()
    call disp%show("isAscendingAll('?Aa')")
    call disp%show( isAscendingAll('?Aa') )
    call disp%skip()
    call disp%show("isAscendingAll('A!b')")
    call disp%show( isAscendingAll('A!b') )
    call disp%skip()
    call disp%show("isAscendingAll('zxw')")
    call disp%show( isAscendingAll('zxw') )
    call disp%skip()
    call disp%show("isAscendingAll('AAA')")
    call disp%show( isAscendingAll('AAA') )
    call disp%skip()

    call disp%skip()
    call disp%show("isAscendingAll([character(0) ::])")
    call disp%show( isAscendingAll([character(0) ::]) )
    call disp%skip()
    call disp%show("isAscendingAll(['?', 'A', 'a'])")
    call disp%show( isAscendingAll(['?', 'A', 'a']) )
    call disp%skip()
    call disp%show("isAscendingAll(['A', '!', 'b'])")
    call disp%show( isAscendingAll(['A', '!', 'b']) )
    call disp%skip()
    call disp%show("isAscendingAll(['z', 'x', 'w'])")
    call disp%show( isAscendingAll(['z', 'x', 'w']) )
    call disp%skip()
    call disp%show("isAscendingAll(['A', 'A', 'A'])")
    call disp%show( isAscendingAll(['A', 'A', 'A']) )
    call disp%skip()

    call disp%skip()
    call disp%show("isAscendingAll([integer ::])")
    call disp%show( isAscendingAll([integer ::]) )
    call disp%skip()
    call disp%show("isAscendingAll([+1, +2, +3])")
    call disp%show( isAscendingAll([+1, +2, +3]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1, -2, -3])")
    call disp%show( isAscendingAll([-1, -2, -3]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1, +2, -3])")
    call disp%show( isAscendingAll([-1, +2, -3]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1, -1, -1])")
    call disp%show( isAscendingAll([-1, -1, -1]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isAscendingAll([logical ::])")
    call disp%show( isAscendingAll([logical ::]) )
    call disp%skip()
    call disp%show("isAscendingAll([.false., .false., .true.])")
    call disp%show( isAscendingAll([.false., .false., .true.]) )
    call disp%skip()
    call disp%show("isAscendingAll([.true., .false., .false.])")
    call disp%show( isAscendingAll([.true., .false., .false.]) )
    call disp%skip()
    call disp%show("isAscendingAll([.false., .true., .false.])")
    call disp%show( isAscendingAll([.false., .true., .false.]) )
    call disp%skip()
    call disp%show("isAscendingAll([.true., .true., .true.])")
    call disp%show( isAscendingAll([.true., .true., .true.]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isAscendingAll([complex ::])")
    call disp%show( isAscendingAll([complex ::]) )
    call disp%skip()
    call disp%show("isAscendingAll([(+1., -1.), (+2., -2.), (+3., -3.)])")
    call disp%show( isAscendingAll([(+1., -1.), (+2., -2.), (+3., -3.)]) )
    call disp%skip()
    call disp%show("isAscendingAll([(-1., +1.), (-2., +2.), (-3., +3.)])")
    call disp%show( isAscendingAll([(-1., +1.), (-2., +2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isAscendingAll([(-1., +1.), (+2., -2.), (-3., +3.)])")
    call disp%show( isAscendingAll([(-1., +1.), (+2., -2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isAscendingAll([(-1., +1.), (-1., +1.), (-1., +1.)])")
    call disp%show( isAscendingAll([(-1., +1.), (-1., +1.), (-1., +1.)]) )
    call disp%skip()
    call disp%show("isAscendingAll([(-1., +1.), (-1., -2.), (-1., +3.)])")
    call disp%show( isAscendingAll([(-1., +1.), (-1., -2.), (-1., +3.)]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isAscendingAll([real ::])")
    call disp%show( isAscendingAll([real ::]) )
    call disp%skip()
    call disp%show("isAscendingAll([+1., +2., +3.])")
    call disp%show( isAscendingAll([+1., +2., +3.]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1., -2., -3.])")
    call disp%show( isAscendingAll([-1., -2., -3.]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1., +2., -3.])")
    call disp%show( isAscendingAll([-1., +2., -3.]) )
    call disp%skip()
    call disp%show("isAscendingAll([-1., -1., -1.])")
    call disp%show( isAscendingAll([-1., -1., -1.]) )
    call disp%skip()

#if !__GFORTRAN__
    !   \bug
    !   Intel ifort 2022.3 cannot handle aliases for pdt names (e.g., strc => css_pdt).
    call disp%skip()
    call disp%show("isAscendingAll([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')])")
    call disp%show( isAscendingAll([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')]) )
    call disp%skip()
    call disp%show("isAscendingAll([css_pdt('string'), css_pdt('is'), css_pdt('sorted')])")
    call disp%show( isAscendingAll([css_pdt('string'), css_pdt('is'), css_pdt('sorted')]) )
    call disp%skip()
    call disp%show("isAscendingAll([css_pdt('same string'), css_pdt('same '), css_pdt('same')])")
    call disp%show( isAscendingAll([css_pdt('same string'), css_pdt('same '), css_pdt('same')]) )
    call disp%skip()
#endif

end program example