program example

    use pm_kind, only: SK, IK, LK ! all intrinsic types and kinds are supported.
    use pm_arraySort, only: isSorted
    use pm_io, only: display_type

    implicit none

    type(display_type) :: disp

    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("isSorted('')")
    call disp%show( isSorted('') )
    call disp%skip()
    call disp%show("isSorted('?Aa')")
    call disp%show( isSorted('?Aa') )
    call disp%skip()
    call disp%show("isSorted('A!b')")
    call disp%show( isSorted('A!b') )
    call disp%skip()
    call disp%show("isSorted('zxw')")
    call disp%show( isSorted('zxw') )
    call disp%skip()
    call disp%show("isSorted('AAA')")
    call disp%show( isSorted('AAA') )
    call disp%skip()

    call disp%skip()
    call disp%show("isSorted([character(0) ::])")
    call disp%show( isSorted([character(0) ::]) )
    call disp%skip()
    call disp%show("isSorted(['?', 'A', 'a'])")
    call disp%show( isSorted(['?', 'A', 'a']) )
    call disp%skip()
    call disp%show("isSorted(['A', '!', 'b'])")
    call disp%show( isSorted(['A', '!', 'b']) )
    call disp%skip()
    call disp%show("isSorted(['z', 'x', 'w'])")
    call disp%show( isSorted(['z', 'x', 'w']) )
    call disp%skip()
    call disp%show("isSorted(['A', 'A', 'A'])")
    call disp%show( isSorted(['A', 'A', 'A']) )
    call disp%skip()

    call disp%skip()
    call disp%show("isSorted([integer ::])")
    call disp%show( isSorted([integer ::]) )
    call disp%skip()
    call disp%show("isSorted([+1, +2, +3])")
    call disp%show( isSorted([+1, +2, +3]) )
    call disp%skip()
    call disp%show("isSorted([-1, -2, -3])")
    call disp%show( isSorted([-1, -2, -3]) )
    call disp%skip()
    call disp%show("isSorted([-1, +2, -3])")
    call disp%show( isSorted([-1, +2, -3]) )
    call disp%skip()
    call disp%show("isSorted([-1, -1, -1])")
    call disp%show( isSorted([-1, -1, -1]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isSorted([logical ::])")
    call disp%show( isSorted([logical ::]) )
    call disp%skip()
    call disp%show("isSorted([.false., .false., .true.])")
    call disp%show( isSorted([.false., .false., .true.]) )
    call disp%skip()
    call disp%show("isSorted([.true., .false., .false.])")
    call disp%show( isSorted([.true., .false., .false.]) )
    call disp%skip()
    call disp%show("isSorted([.false., .true., .false.])")
    call disp%show( isSorted([.false., .true., .false.]) )
    call disp%skip()
    call disp%show("isSorted([.true., .true., .true.])")
    call disp%show( isSorted([.true., .true., .true.]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isSorted([complex ::])")
    call disp%show( isSorted([complex ::]) )
    call disp%skip()
    call disp%show("isSorted([(+1., -1.), (+2., -2.), (+3., -3.)])")
    call disp%show( isSorted([(+1., -1.), (+2., -2.), (+3., -3.)]) )
    call disp%skip()
    call disp%show("isSorted([(-1., +1.), (-2., +2.), (-3., +3.)])")
    call disp%show( isSorted([(-1., +1.), (-2., +2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isSorted([(-1., +1.), (+2., -2.), (-3., +3.)])")
    call disp%show( isSorted([(-1., +1.), (+2., -2.), (-3., +3.)]) )
    call disp%skip()
    call disp%show("isSorted([(-1., +1.), (-1., +1.), (-1., +1.)])")
    call disp%show( isSorted([(-1., +1.), (-1., +1.), (-1., +1.)]) )
    call disp%skip()
    call disp%show("isSorted([(-1., +1.), (-1., -2.), (-1., +3.)])")
    call disp%show( isSorted([(-1., +1.), (-1., -2.), (-1., +3.)]) )
    call disp%skip()

    call disp%skip()
    call disp%show("isSorted([real ::])")
    call disp%show( isSorted([real ::]) )
    call disp%skip()
    call disp%show("isSorted([+1., +2., +3.])")
    call disp%show( isSorted([+1., +2., +3.]) )
    call disp%skip()
    call disp%show("isSorted([-1., -2., -3.])")
    call disp%show( isSorted([-1., -2., -3.]) )
    call disp%skip()
    call disp%show("isSorted([-1., +2., -3.])")
    call disp%show( isSorted([-1., +2., -3.]) )
    call disp%skip()
    call disp%show("isSorted([-1., -1., -1.])")
    call disp%show( isSorted([-1., -1., -1.]) )
    call disp%skip()

#if PDT_ENABLED
    !   \bug
    !   Intel ifort 2022.3 cannot handle aliases for pdt names (e.g., strc => css_pdt).
    block
        use pm_container, only: css_pdt
        call disp%skip()
        call disp%show("isSorted([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')])")
        call disp%show( isSorted([css_pdt('is'), css_pdt(  'sorted'), css_pdt('string')]) )
        call disp%skip()
        call disp%show("isSorted([css_pdt('string'), css_pdt('is'), css_pdt('sorted')])")
        call disp%show( isSorted([css_pdt('string'), css_pdt('is'), css_pdt('sorted')]) )
        call disp%skip()
        call disp%show("isSorted([css_pdt('same string'), css_pdt('same '), css_pdt('same')])")
        call disp%show( isSorted([css_pdt('same string'), css_pdt('same '), css_pdt('same')]) )
        call disp%skip()
    end block
#endif

end program example