program example

    use pm_kind, only: IK, LK
    use pm_kind, only: SK ! All other processor string kinds are also suppored.
    use pm_kind, only: IKL, IKS, IKD, IKH
    use pm_kind, only: CKL, CKS, CKD, CKH
    use pm_kind, only: RKL, RKS, RKD, RKH
    use pm_io, only: display_type
    use pm_val2str, only: setStr

    implicit none

    integer(IK)         :: lenstr
    character(1023, SK) :: str

    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 'paramonte')")
                    call setStr(str, lenstr, 'paramonte')
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, '  paramonte')")
                    call setStr(str, lenstr, '  paramonte')
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, '  paramonte  ')")
                    call setStr(str, lenstr, '  paramonte  ')
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, ['paramonte', 'library  '])")
                    call setStr(str, lenstr, ['paramonte', 'library  '])
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, ['paramonte  ', '  library  '])")
                    call setStr(str, lenstr, ['paramonte  ', '  library  '])
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, .true.)")
                    call setStr(str, lenstr, .true.)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, .false.)")
                    call setStr(str, lenstr, .false.)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, -1_IKL)")
                    call setStr(str, lenstr, -1_IKL)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 1234_IKS, signed = .true._LK)")
                    call setStr(str, lenstr, 1234_IKS, signed = .true._LK)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 987654321_IKD)")
                    call setStr(str, lenstr, 987654321_IKD)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 987654321_IKH)")
                    call setStr(str, lenstr, 987654321_IKH)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 987654321_IKD, format = '(I15)')")
                    call setStr(str, lenstr, 987654321_IKD, format = '(I15)')
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 123._RKL)")
                    call setStr(str, lenstr, 123._RKL)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 123._RKS)")
                    call setStr(str, lenstr, 123._RKS)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, 123._RKD, format = '(E25.15)') ! use scientific notation with a width of 25.")
                    call setStr(str, lenstr, 123._RKD, format = '(E25.15)')
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, [huge(0._RKH), -123456._RKH])")
                    call setStr(str, lenstr, [huge(0._RKH), -123456._RKH])
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, (1._CKH,-1._CKH))")
                    call setStr(str, lenstr, (1._CKH,-1._CKH))
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, [(1._CKD,-1._CKD), (2._CKD,-2._CKD)], signed = .true._LK)")
                    call setStr(str, lenstr, [(1._CKD,-1._CKD), (2._CKD,-2._CKD)], signed = .true._LK)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

    call disp%skip()
    call disp%show("call setStr(str, lenstr, reshape([(1._CKS,-1._CKS), (2._CKS,-2._CKS), (3._CKS,-3._CKS), (4._CKS,-4._CKS)], shape = [2,2]), signed = .true._LK) ! input object of rank 2")
                    call setStr(str, lenstr, reshape([(1._CKS,-1._CKS), (2._CKS,-2._CKS), (3._CKS,-3._CKS), (4._CKS,-4._CKS)], shape = [2,2]), signed = .true._LK)
    call disp%show("lenstr")
    call disp%show( lenstr )
    call disp%show("str(1:lenstr)")
    call disp%show( str(1:lenstr) , deliml = SK_"""" )
    call disp%skip()

end program example