program example

    use pm_kind, only: LK, SK
    use pm_io, only: display_type
    use pm_kind, only: IK, RKS, RKD, RKH, CKS, CKD, CKH
    use pm_arraySpace, only: setLogSpace 

    implicit none

    real(RKH)       :: logSpace_RKH(4)
    real(RKD)       :: logSpace_RKD(4)
    real(RKS)       :: logSpace_RKS(4)
    complex(CKH)    :: logSpace_CKH(4)
    complex(CKD)    :: logSpace_CKD(4)
    complex(CKS)    :: logSpace_CKS(4)

    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("Generate real logspace.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%skip()
    call disp%show("!%%%%%%%%%%")
    call disp%show("32-bit real")
    call disp%show("!%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS)")
                    call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, fopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, fopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, lopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, lopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, fopen = .true._LK, lopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 0._RKS, 4._RKS, fopen = .true._LK, lopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )

    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS)")
                    call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, fopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, fopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, lopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, lopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )
    call disp%show("call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, fopen = .true._LK, lopen = .true._LK, base = 10._RKS)")
                    call setLogSpace(logSpace_RKS, 4._RKS, 0._RKS, fopen = .true._LK, lopen = .true._LK, base = 10._RKS)
    call disp%show("logSpace_RKS")
    call disp%show( logSpace_RKS )

    call disp%skip()
    call disp%show("!%%%%%%%%%%")
    call disp%show("64-bit real")
    call disp%show("!%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD)")
                    call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, fopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, fopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, lopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, lopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, fopen = .true._LK, lopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 0._RKD, 4._RKD, fopen = .true._LK, lopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    
    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD)")
                    call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, fopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, fopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, lopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, lopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )
    call disp%show("call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, fopen = .true._LK, lopen = .true._LK, base = 10._RKD)")
                    call setLogSpace(logSpace_RKD, 4._RKD, 0._RKD, fopen = .true._LK, lopen = .true._LK, base = 10._RKD)
    call disp%show("logSpace_RKD")
    call disp%show( logSpace_RKD )

    call disp%skip()
    call disp%show("!%%%%%%%%%%%")
    call disp%show("128-bit real")
    call disp%show("!%%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH)")
                    call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, fopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, fopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, lopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, lopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, fopen = .true._LK, lopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 0._RKH, 4._RKH, fopen = .true._LK, lopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )

    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH)")
                    call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, fopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, fopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, lopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, lopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )
    call disp%show("call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, fopen = .true._LK, lopen = .true._LK, base = 10._RKH)")
                    call setLogSpace(logSpace_RKH, 4._RKH, 0._RKH, fopen = .true._LK, lopen = .true._LK, base = 10._RKH)
    call disp%show("logSpace_RKH")
    call disp%show( logSpace_RKH )


    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("Generate complex logspace.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()


    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%")
    call disp%show("32-bit complex")
    call disp%show("!%%%%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_CKS, (1._CKS,1._CKS), (4._CKS,4._CKS))")
                    call setLogSpace(logSpace_CKS, (1._CKS,1._CKS), (4._CKS,4._CKS))
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (1._CKS,1._CKS), (4._CKS,4._CKS), base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (1._CKS,1._CKS), (4._CKS,4._CKS), base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), fopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), fopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), lopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), lopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), fopen = .true._LK, lopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (0._CKS,0._CKS), (4._CKS,4._CKS), fopen = .true._LK, lopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )

    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS))")
                    call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS))
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), fopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), fopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), lopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), lopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )
    call disp%show("call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), fopen = .true._LK, lopen = .true._LK, base = 10._CKS)")
                    call setLogSpace(logSpace_CKS, (4._CKS,-4._CKS), (-4._CKS,+4._CKS), fopen = .true._LK, lopen = .true._LK, base = 10._CKS)
    call disp%show("logSpace_CKS")
    call disp%show( logSpace_CKS )

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%")
    call disp%show("64-bit complex")
    call disp%show("!%%%%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD))")
                    call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD))
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), fopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), fopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), lopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), lopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), fopen = .true._LK, lopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (0._CKD,0._CKD), (4._CKD,4._CKD), fopen = .true._LK, lopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )

    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD))")
                    call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD))
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), fopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), fopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), lopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), lopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )
    call disp%show("call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), fopen = .true._LK, lopen = .true._LK, base = 10._CKD)")
                    call setLogSpace(logSpace_CKD, (4._CKD,-4._CKD), (-4._CKD,+4._CKD), fopen = .true._LK, lopen = .true._LK, base = 10._CKD)
    call disp%show("logSpace_CKD")
    call disp%show( logSpace_CKD )

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%")
    call disp%show("128-bit complex")
    call disp%show("!%%%%%%%%%%%%%%")
    call disp%skip()

    call disp%show("call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH))")
                    call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH))
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), fopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), fopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), lopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), lopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), fopen = .true._LK, lopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (0._CKH,0._CKH), (4._CKH,4._CKH), fopen = .true._LK, lopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )

    ! Generate sequence in reverse.

    call disp%show("call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH))")
                    call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH))
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), fopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), fopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), lopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), lopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )
    call disp%show("call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), fopen = .true._LK, lopen = .true._LK, base = 10._CKH)")
                    call setLogSpace(logSpace_CKH, (4._CKH,-4._CKH), (-4._CKH,+4._CKH), fopen = .true._LK, lopen = .true._LK, base = 10._CKH)
    call disp%show("logSpace_CKH")
    call disp%show( logSpace_CKH )

end program example