program example

    use pm_kind, only: SK, IK, LK
    use pm_sampleQuan, only: getQuan, neimean, neinear, neinext, neiprev, piwilin
    use pm_arraySpace, only: getLinSpace
    use pm_distNorm, only: getNormRand
    use pm_distNorm, only: getNormLogPDF
    use pm_distPois, only: getPoisLogPMF
    use pm_distPois, only: getPoisRand
    use pm_distUnif, only: getUnifRand
    use pm_arrayFill, only: getFilled
    use pm_io, only: getErrTableWrite
    use pm_io, only: display_type

    implicit none

    integer(IK) :: iprob, ndim, nsam, itry, ntry = 5
    integer(IK), allocatable :: iweight(:)
    type(display_type) :: disp

    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%")
    call disp%show("!1D sample quantile.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:), prob(:), quan(:)
        call disp%skip()
        call disp%show("sample = [10, 7, 4, 3, 2, 1, 0]")
                        sample = [10, 7, 4, 3, 2, 1, 0]
        call disp%show("prob = [0., .25, .5, .75, .9, 1.]")
                        prob = [0., .25, .5, .75, .9, 1.]
        call disp%show("quan = getQuan(neimean, prob, sample)")
                        quan = getQuan(neimean, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinear, prob, sample)")
                        quan = getQuan(neinear, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinext, prob, sample)")
                        quan = getQuan(neinext, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neiprev, prob, sample)")
                        quan = getQuan(neiprev, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(piwilin, prob, sample)")
                        quan = getQuan(piwilin, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("do iprob = 1, size(prob)")
        call disp%show("    quan(iprob) = getQuan(piwilin, prob(iprob), sample)")
        call disp%show("end do")
                        do iprob = 1, size(prob)
                            quan(iprob) = getQuan(piwilin, prob(iprob), sample)
                        end do
        call disp%show("quan")
        call disp%show( quan )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!1D frequency/reliability-weighted sample quantile.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:), prob(:), quan(:)
        call disp%skip()
        call disp%show("sample = [10, 7, 4, 3, 2, 1, 0]")
                        sample = [10, 7, 4, 3, 2, 1, 0]
        call disp%show("iweight = getUnifRand(1, 9, size(sample, 1, IK))")
                        iweight = getUnifRand(1, 9, size(sample, 1, IK))
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("prob = [0., .25, .5, .75, .9, 1.]")
                        prob = [0., .25, .5, .75, .9, 1.]
        call disp%show("quan = getQuan(neimean, prob, sample)")
                        quan = getQuan(neimean, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinear, prob, sample, iweight)")
                        quan = getQuan(neinear, prob, sample, iweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinext, prob, sample, iweight)")
                        quan = getQuan(neinext, prob, sample, iweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neiprev, prob, sample, iweight)")
                        quan = getQuan(neiprev, prob, sample, iweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(piwilin, prob, sample, iweight, sum(iweight))")
                        quan = getQuan(piwilin, prob, sample, iweight, sum(iweight))
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("do iprob = 1, size(prob)")
        call disp%show("    quan(iprob) = getQuan(piwilin, prob(iprob), sample, iweight)")
        call disp%show("end do")
                        do iprob = 1, size(prob)
                            quan(iprob) = getQuan(piwilin, prob(iprob), sample, iweight)
                        end do
        call disp%show("quan")
        call disp%show( quan )
        call disp%skip()
    end block

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:), prob(:), quan(:)
        real(TKC), allocatable :: rweight(:)
        call disp%skip()
        call disp%show("sample = [10, 7, 4, 3, 2, 1, 0]")
                        sample = [10, 7, 4, 3, 2, 1, 0]
        call disp%show("rweight = exp(getNormLogPDF(getFilled(0._TKC, size(sample, 1, IK))))")
                        rweight = exp(getNormLogPDF(getFilled(0._TKC, size(sample, 1, IK))))
        call disp%show("rweight")
        call disp%show( rweight )
        call disp%show("prob = [0., .25, .5, .75, .9, 1.]")
                        prob = [0., .25, .5, .75, .9, 1.]
        call disp%show("quan = getQuan(neimean, prob, sample)")
                        quan = getQuan(neimean, prob, sample)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinear, prob, sample, rweight)")
                        quan = getQuan(neinear, prob, sample, rweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neinext, prob, sample, rweight)")
                        quan = getQuan(neinext, prob, sample, rweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(neiprev, prob, sample, rweight)")
                        quan = getQuan(neiprev, prob, sample, rweight)
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("quan = getQuan(piwilin, prob, sample, rweight, sum(rweight))")
                        quan = getQuan(piwilin, prob, sample, rweight, sum(rweight))
        call disp%show("quan")
        call disp%show( quan )
        call disp%show("do iprob = 1, size(prob)")
        call disp%show("    quan(iprob) = getQuan(piwilin, prob(iprob), sample, rweight)")
        call disp%show("end do")
                        do iprob = 1, size(prob)
                            quan(iprob) = getQuan(piwilin, prob(iprob), sample, rweight)
                        end do
        call disp%show("quan")
        call disp%show( quan )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%")
    call disp%show("!2D sample quantile.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:,:), prob(:), quan1(:), quan2(:,:)
        integer(IK) :: nsam, nprob, dim
        call disp%skip()
        call disp%show("dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)")
                        dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)
        call disp%show("[ndim, nsam, nprob]")
        call disp%show( [ndim, nsam, nprob] )
        call disp%show("sample = getPoisRand(getFilled(10., ndim, nsam))")
                        sample = getPoisRand(getFilled(10., ndim, nsam))
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("prob = getLinSpace(0., 1., nprob)")
                        prob = getLinSpace(0., 1., nprob)
        call disp%show("prob")
        call disp%show( prob )
        call disp%show("quan2 = getQuan(neimean, prob, sample, dim)")
                        quan2 = getQuan(neimean, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinear, prob, sample, dim)")
                        quan2 = getQuan(neinear, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinext, prob, sample, dim)")
                        quan2 = getQuan(neinext, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neiprev, prob, sample, dim)")
                        quan2 = getQuan(neiprev, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(piwilin, prob, sample, dim)")
                        quan2 = getQuan(piwilin, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan1 = getQuan(neimean, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neimean, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinear, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neinear, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinext, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neinext, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neiprev, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neiprev, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(piwilin, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(piwilin, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%skip()
    end block

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:,:), prob(:), quan1(:), quan2(:,:)
        integer(IK) :: nsam, nprob, dim
        call disp%skip()
        call disp%show("dim = 1; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)")
                        dim = 1; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)
        call disp%show("[ndim, nsam, nprob]")
        call disp%show( [ndim, nsam, nprob] )
        call disp%show("sample = getPoisRand(getFilled(10., nsam, ndim))")
                        sample = getPoisRand(getFilled(10., nsam, ndim))
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("prob = getLinSpace(0., 1., nprob)")
                        prob = getLinSpace(0., 1., nprob)
        call disp%show("prob")
        call disp%show( prob )
        call disp%show("quan2 = getQuan(neimean, prob, sample, dim)")
                        quan2 = getQuan(neimean, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinear, prob, sample, dim)")
                        quan2 = getQuan(neinear, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinext, prob, sample, dim)")
                        quan2 = getQuan(neinext, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neiprev, prob, sample, dim)")
                        quan2 = getQuan(neiprev, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(piwilin, prob, sample, dim)")
                        quan2 = getQuan(piwilin, prob, sample, dim)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan1 = getQuan(neimean, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neimean, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinear, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neinear, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinext, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neinext, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neiprev, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(neiprev, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(piwilin, prob(nprob/2), sample, dim)")
                        quan1 = getQuan(piwilin, prob(nprob/2), sample, dim)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!2D frequency/reliability-weighted sample quantile.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:,:), prob(:), quan1(:), quan2(:,:)
        integer(IK) :: nsam, nprob, dim
        call disp%skip()
        call disp%show("dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)")
                        dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)
        call disp%show("[ndim, nsam, nprob]")
        call disp%show( [ndim, nsam, nprob] )
        call disp%show("sample = getPoisRand(getFilled(10., ndim, nsam))")
                        sample = getPoisRand(getFilled(10., ndim, nsam))
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("iweight = getUnifRand(1, 9, nsam)")
                        iweight = getUnifRand(1, 9, nsam)
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("prob = getLinSpace(0., 1., nprob)")
                        prob = getLinSpace(0., 1., nprob)
        call disp%show("prob")
        call disp%show( prob )
        call disp%show("quan2 = getQuan(neimean, prob, sample, dim, iweight)")
                        quan2 = getQuan(neimean, prob, sample, dim, iweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinear, prob, sample, dim, iweight)")
                        quan2 = getQuan(neinear, prob, sample, dim, iweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinext, prob, sample, dim, iweight)")
                        quan2 = getQuan(neinext, prob, sample, dim, iweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neiprev, prob, sample, dim, iweight)")
                        quan2 = getQuan(neiprev, prob, sample, dim, iweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(piwilin, prob, sample, dim, iweight)")
                        quan2 = getQuan(piwilin, prob, sample, dim, iweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan1 = getQuan(neimean, prob(nprob/2), sample, dim, iweight)")
                        quan1 = getQuan(neimean, prob(nprob/2), sample, dim, iweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinear, prob(nprob/2), sample, dim, iweight)")
                        quan1 = getQuan(neinear, prob(nprob/2), sample, dim, iweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinext, prob(nprob/2), sample, dim, iweight)")
                        quan1 = getQuan(neinext, prob(nprob/2), sample, dim, iweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neiprev, prob(nprob/2), sample, dim, iweight)")
                        quan1 = getQuan(neiprev, prob(nprob/2), sample, dim, iweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(piwilin, prob(nprob/2), sample, dim, iweight)")
                        quan1 = getQuan(piwilin, prob(nprob/2), sample, dim, iweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!2D frequency/reliability-weighted sample quantile.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKC => RKS ! all processor kinds are supported.
        real(TKC), allocatable :: sample(:,:), prob(:), quan1(:), quan2(:,:)
        real(TKC), allocatable :: rweight(:)
        integer(IK) :: nsam, nprob, dim
        call disp%skip()
        call disp%show("dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)")
                        dim = 2; ndim = getUnifRand(1, 3); nsam = getUnifRand(5, 10); nprob = getUnifRand(3, 9)
        call disp%show("[ndim, nsam, nprob]")
        call disp%show( [ndim, nsam, nprob] )
        call disp%show("sample = getPoisRand(getFilled(10., ndim, nsam))")
                        sample = getPoisRand(getFilled(10., ndim, nsam))
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("rweight = getUnifRand(1, 9, nsam)")
                        rweight = getUnifRand(1, 9, nsam)
        call disp%show("rweight")
        call disp%show( rweight )
        call disp%show("prob = getLinSpace(0., 1., nprob)")
                        prob = getLinSpace(0., 1., nprob)
        call disp%show("prob")
        call disp%show( prob )
        call disp%show("quan2 = getQuan(neimean, prob, sample, dim, rweight)")
                        quan2 = getQuan(neimean, prob, sample, dim, rweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinear, prob, sample, dim, rweight)")
                        quan2 = getQuan(neinear, prob, sample, dim, rweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neinext, prob, sample, dim, rweight)")
                        quan2 = getQuan(neinext, prob, sample, dim, rweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(neiprev, prob, sample, dim, rweight)")
                        quan2 = getQuan(neiprev, prob, sample, dim, rweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan2 = getQuan(piwilin, prob, sample, dim, rweight)")
                        quan2 = getQuan(piwilin, prob, sample, dim, rweight)
        call disp%show("quan2")
        call disp%show( quan2 )
        call disp%show("quan1 = getQuan(neimean, prob(nprob/2), sample, dim, rweight)")
                        quan1 = getQuan(neimean, prob(nprob/2), sample, dim, rweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinear, prob(nprob/2), sample, dim, rweight)")
                        quan1 = getQuan(neinear, prob(nprob/2), sample, dim, rweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neinext, prob(nprob/2), sample, dim, rweight)")
                        quan1 = getQuan(neinext, prob(nprob/2), sample, dim, rweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(neiprev, prob(nprob/2), sample, dim, rweight)")
                        quan1 = getQuan(neiprev, prob(nprob/2), sample, dim, rweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%show("quan1 = getQuan(piwilin, prob(nprob/2), sample, dim, rweight)")
                        quan1 = getQuan(piwilin, prob(nprob/2), sample, dim, rweight)
        call disp%show("quan1")
        call disp%show( quan1 )
        call disp%skip()
    end block

end program example