program example

    use pm_kind, only: SK, IK, LK
    use pm_sampleMean, only: getMean
    use pm_sampleMean, only: setMean
    use pm_sampleShift, only: getShifted
    use pm_arraySpace, only: getLinSpace
    use pm_arrayResize, only: setResized
    use pm_distUnif, only: getUnifRand
    use pm_arrayFill, only: getFilled
    use pm_sampleCov, only: uppDia
    use pm_sampleCov, only: lowDia
    use pm_sampleCov, only: setCov
    use pm_io, only: display_type
    use pm_io, only: getFormat

    implicit none

    integer(IK) :: itry, ntry = 10
    type(display_type) :: disp
    character(:), allocatable :: format
    disp = display_type(file = "main.out.F90")

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Convert correlation matrix and standard deviation to covariance matrix.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKG => RKS ! All other real types are also supported.
        use pm_matrixCopy, only: setMatCopy, rdpack
        use pm_distCov, only: getCovRand
        integer(IK) :: ndim
        real(TKG), allocatable :: cov(:,:), cor(:,:), std(:)
        format = getFormat(mold = [0._TKG], ed = SK_"es", signed = .true._LK)
        do itry = 1, ntry
            call disp%skip()
            call disp%show("ndim = getUnifRand(1, 7)")
                            ndim = getUnifRand(1, 7)
            call disp%show("ndim")
            call disp%show( ndim )
            call disp%show("std = getUnifRand(1, 10, ndim)")
                            std = getUnifRand(1, 10, ndim)
            call disp%show("std")
            call disp%show( std , format = format )
            call disp%show("cor = getCovRand(1., ndim)")
                            cor = getCovRand(1., ndim)
            call disp%show("cor")
            call disp%show( cor , format = format )
            call disp%show("cov = getFilled(0._TKG, ndim, ndim + 1)")
                            cov = getFilled(0._TKG, ndim, ndim + 1)
            call disp%show("call setMatCopy(cov(1:ndim, 1:ndim), rdpack, cor, rdpack, lowDia)")
                            call setMatCopy(cov(1:ndim, 1:ndim), rdpack, cor, rdpack, lowDia)
            call disp%show("cov")
            call disp%show( cov , format = format )
            call disp%show("call setCov(cov(1:ndim, 2:ndim+1), uppDia, cov(1:ndim, 1:ndim), lowDia, std) ! convert lower-triangle correlation matrix to upper-triangle covariance matrix.")
                            call setCov(cov(1:ndim, 2:ndim+1), uppDia, cov(1:ndim, 1:ndim), lowDia, std)
            call disp%show("cov")
            call disp%show( cov , format = format )
            call disp%skip()
            call disp%show("cov = getFilled(0._TKG, ndim, ndim + 1)")
                            cov = getFilled(0._TKG, ndim, ndim + 1)
            call disp%show("call setMatCopy(cov(1:ndim, 2:ndim+1), rdpack, cor, rdpack, uppDia)")
                            call setMatCopy(cov(1:ndim, 2:ndim+1), rdpack, cor, rdpack, uppDia)
            call disp%show("cov")
            call disp%show( cov , format = format )
            call disp%show("call setCov(cov(1:ndim, 1:ndim), lowDia, cov(1:ndim, 2:ndim+1), uppDia, std) ! convert upper-triangle correlation matrix to lower-triangle covariance matrix.")
                            call setCov(cov(1:ndim, 1:ndim), lowDia, cov(1:ndim, 2:ndim+1), uppDia, std)
            call disp%show("cov")
            call disp%show( cov , format = format )
            call disp%skip()
        end do
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the covariance matrix of a 2-D sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKG => RKS ! All other real types are also supported.
        real(TKG), allocatable :: sample(:,:), samShifted(:,:), cov(:,:), mean(:)
        integer(IK) :: ndim, nsam, dim
        call disp%show("ndim = 2; nsam = 10; dim = 2")
                        ndim = 2; nsam = 10; dim = 2
        call disp%show("sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])")
                        sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("mean = getMean(sample, dim)")
                        mean = getMean(sample, dim)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("samShifted = getShifted(sample, dim, -mean)")
                        samShifted = getShifted(sample, dim, -mean)
        call disp%show("samShifted")
        call disp%show( samShifted )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, sample, dim)")
                        call setCov(cov, uppDia, mean, sample, dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, samShifted, dim) ! same result as above.")
                        call setCov(cov, uppDia, samShifted, dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, sample, dim)")
                        call setCov(cov, lowDia, mean, sample, dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, samShifted, dim) ! same result as above.")
                        call setCov(cov, lowDia, samShifted, dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, transpose(sample), dim)")
                        call setCov(cov, uppDia, mean, transpose(sample), dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, transpose(samShifted), dim) ! same result as above.")
                        call setCov(cov, uppDia, transpose(samShifted), dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, transpose(sample), dim)")
                        call setCov(cov, lowDia, mean, transpose(sample), dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, transpose(samShifted), dim) ! same result as above.")
                        call setCov(cov, lowDia, transpose(samShifted), dim)
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, mean, sample(1,:), sample(2,:))")
                        call setCov(cov, mean, sample(1,:), sample(2,:))
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, samShifted(1,:), samShifted(2,:)) ! same result as above.")
                        call setCov(cov, samShifted(1,:), samShifted(2,:))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
    end block

    call disp%skip()
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!Compute the biased covariance matrix of a weighted 2-D sample.")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
    call disp%skip()

    block
        use pm_kind, only: TKG => RKS ! All other real types are also supported.
        real(TKG) :: rweisum
        integer(IK) :: iweisum
        real(TKG), allocatable :: rweight(:)
        integer(IK), allocatable :: iweight(:)
        real(TKG), allocatable :: sample(:,:), samShifted(:,:), cov(:,:), mean(:)
        integer(IK) :: ndim, nsam, dim
        call disp%show("ndim = 2; nsam = 10; dim = 2")
                        ndim = 2; nsam = 10; dim = 2
        call disp%show("sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])")
                        sample = reshape(getUnifRand(1, 20, ndim * nsam), shape = [ndim, nsam], order = [2, 1])
        call disp%show("sample")
        call disp%show( sample )
        call disp%show("call setResized(mean, ndim)")
                        call setResized(mean, ndim)
        call disp%show("iweight = getUnifRand(1, 10, nsam) ! integer-valued weights.")
                        iweight = getUnifRand(1, 10, nsam) ! integer-valued weights.
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("call setMean(mean, sample, dim, iweight, iweisum)")
                        call setMean(mean, sample, dim, iweight, iweisum)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("iweisum")
        call disp%show( iweisum )
        call disp%show("rweight = iweight ! or real-valued weights.")
                        rweight = iweight ! or real-valued weights.
        call disp%show("iweight")
        call disp%show( iweight )
        call disp%show("call setMean(mean, sample, dim, rweight, rweisum)")
                        call setMean(mean, sample, dim, rweight, rweisum)
        call disp%show("mean")
        call disp%show( mean )
        call disp%show("rweisum")
        call disp%show( rweisum )

        call disp%skip()
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%show("!Compute the covariance matrix integer weights.")
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%skip()

        call disp%show("samShifted = getShifted(sample, dim, -mean)")
                        samShifted = getShifted(sample, dim, -mean)
        call disp%show("samShifted")
        call disp%show( samShifted )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, sample, dim, iweight, iweisum)")
                        call setCov(cov, uppDia, mean, sample, dim, iweight, iweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, samShifted, dim, iweight, sum(iweight)) ! same result as above.")
                        call setCov(cov, uppDia, samShifted, dim, iweight, sum(iweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, sample, dim, iweight, iweisum)")
                        call setCov(cov, lowDia, mean, sample, dim, iweight, iweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, samShifted, dim, iweight, sum(iweight)) ! same result as above.")
                        call setCov(cov, lowDia, samShifted, dim, iweight, sum(iweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, transpose(sample), dim, iweight, iweisum)")
                        call setCov(cov, uppDia, mean, transpose(sample), dim, iweight, iweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, transpose(samShifted), dim, iweight, sum(iweight)) ! same result as above.")
                        call setCov(cov, uppDia, transpose(samShifted), dim, iweight, sum(iweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, transpose(sample), dim, iweight, iweisum)")
                        call setCov(cov, lowDia, mean, transpose(sample), dim, iweight, iweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, transpose(samShifted), dim, iweight, sum(iweight)) ! same result as above.")
                        call setCov(cov, lowDia, transpose(samShifted), dim, iweight, sum(iweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, mean, sample(1,:), sample(2,:), iweight, iweisum)")
                        call setCov(cov, mean, sample(1,:), sample(2,:), iweight, iweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, samShifted(1,:), samShifted(2,:), iweight, sum(iweight)) ! same result as above.")
                        call setCov(cov, samShifted(1,:), samShifted(2,:), iweight, sum(iweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()

        call disp%skip()
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%show("!Compute the covariance matrix    real weights.")
        call disp%show("!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        call disp%skip()

        call disp%show("dim = 2_IK")
                        dim = 2_IK
        call disp%show("samShifted = getShifted(sample, dim, -mean)")
                        samShifted = getShifted(sample, dim, -mean)
        call disp%show("samShifted")
        call disp%show( samShifted )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, sample, dim, rweight, rweisum)")
                        call setCov(cov, uppDia, mean, sample, dim, rweight, rweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, samShifted, dim, rweight, sum(rweight)) ! same result as above.")
                        call setCov(cov, uppDia, samShifted, dim, rweight, sum(rweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, sample, dim, rweight, rweisum)")
                        call setCov(cov, lowDia, mean, sample, dim, rweight, rweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, samShifted, dim, rweight, sum(rweight)) ! same result as above.")
                        call setCov(cov, lowDia, samShifted, dim, rweight, sum(rweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the sample covariance along the first dimension.", deliml = SK_'''')
        call disp%skip()
        call disp%show("dim = 1")
                        dim = 1
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, mean, transpose(sample), dim, rweight, rweisum)")
                        call setCov(cov, uppDia, mean, transpose(sample), dim, rweight, rweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, uppDia, transpose(samShifted), dim, rweight, sum(rweight)) ! same result as above.")
                        call setCov(cov, uppDia, transpose(samShifted), dim, rweight, sum(rweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, mean, transpose(sample), dim, rweight, rweisum)")
                        call setCov(cov, lowDia, mean, transpose(sample), dim, rweight, rweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, lowDia, transpose(samShifted), dim, rweight, sum(rweight)) ! same result as above.")
                        call setCov(cov, lowDia, transpose(samShifted), dim, rweight, sum(rweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
        call disp%show("Compute the full sample covariance for a pair of time series.", deliml = SK_'''')
        call disp%skip()
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, mean, sample(1,:), sample(2,:), rweight, rweisum)")
                        call setCov(cov, mean, sample(1,:), sample(2,:), rweight, rweisum)
        call disp%show("cov")
        call disp%show( cov )
        call disp%show("cov = getFilled(0., ndim, ndim)")
                        cov = getFilled(0., ndim, ndim)
        call disp%show("call setCov(cov, samShifted(1,:), samShifted(2,:), rweight, sum(rweight)) ! same result as above.")
                        call setCov(cov, samShifted(1,:), samShifted(2,:), rweight, sum(rweight))
        call disp%show("cov")
        call disp%show( cov )
        call disp%skip()
    end block

end program example