#!/bin/bash
#
# A hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# This hook is inteded to be used by OpenCoarrays developers to ensure
# that they conform to project standards.



set -o errexit
set -o pipefail
set -o nounset
set -o errtrace

__file=commit-msg

err_report() {
    error_code=$?
    echo 2>&1 "Error in $__file in function $1 on line $2"
    exit $error_code
}

trap 'err_report "${FUNCNAME:-.}" $LINENO' ERR

# error message function for writing good commit messages
# shellcheck disable=SC2006,SC2035
error_message () {
    cat <<-EOF
Error: bad commit message format. A copy of your commit message is in:
'.git/COMMIT_EDITMSG'. Please fix it or write a new one according to the
guidlines below.

The first line of a commit message should start with a capitalized imperative
verb used in a phrase to summarize the change. This first line must be less
than 50 characters, followed by an additional blank line. Further detials are
added after these first two lines, and may be up to 72 characters in length.

This is so that '--oneline' formatted 'git log's will contain human readable,
meaningful information, and the summaries on Github.com will also contain
this concise summary. The 72 line limit is to ensure propper formatting on
all terminals.

Here is an example of a good commit message:

"""
Redirect user to the requested page after login

https://github.com/sourceryinstitute/opencoarrays/Issues/29

Users were being redirected to the home page after login, which is less
useful than redirecting to the page they had originally requested before
being redirected to the login form.

* Store requested path in a session variable
* Redirect to the stored location after successfully logging in the user
* Fixes #1
"""

As opposed to doing something bad like this:

'git commit -m "Fix login bug"'

For more information on writting good commit messages,
and keeping a clean history, please see:

 1. https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
 2. http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
 3. https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/

And for funny examples of what not to do, see: http://whatthecommit.com and
http://stopwritingramblingcommitmessages.com
EOF

}

status=0

# Check that the first line of the commit starts with a
# capitalized letter.
if ! (head -n 1 "$1" | grep '^[A-Z]' &>/dev/null ); then
    echo >&2 "First word of commit message must be a capitalized imperative verb."
    echo ""
    status=1
fi

# Check each line for propper length
ln=0
while read -r line; do
    ln+=1
    nchars=$(wc -c <<<"$line")
    if [[ "$ln" -eq "1" ]]; then
      if [[ "$nchars" -gt "51" ]]; then
	echo >&2 "First line of commit message too long ($nchars > 50 chars)"
	echo ""
	status=1
      fi
    elif [[ "$ln" -eq "2" ]]; then
      if [[ "$nchars" -gt "1" ]] && ! grep '^#' <<<"$line" >/dev/null; then
	echo >&2 "Second line of commit message not blank"
	echo ""
	status=1
      fi
    else
      if [[ "$nchars" -gt "72" ]]; then
	echo >&2 "Line $ln of commit message too long ($nchars > 72 chars)"
	echo ""
	status=1
      fi
    fi
done < "$1"

if [[ $status = 0 ]]; then
    exit 0
fi

error_message
exit 1
